/*
 * cmd_rsp_evt.h.h
 *  Created on: 2019/07/04
 *   Author: Richar Huang
 */

#ifndef _CMD_RSP_EVT_
#define _CMD_RSP_EVT_

typedef struct gecko_cmd_packet     CmdPacket;      // richard Add
typedef struct gecko_cmd_packet*    PCmdPacket;    // richard Add
typedef struct gecko_cmd_packet*    PRspPacket;    // richard Add


//From BLE Mesh v1.5
#define Cmd_dfu_reset                                  gecko_cmd_dfu_reset
#define Cmd_dfu_flash_set_addr                         gecko_cmd_dfu_flash_set_address
#define Cmd_dfu_flash_upload                           gecko_cmd_dfu_flash_upload
#define Cmd_dfu_flash_upload_finish                    gecko_cmd_dfu_flash_upload_finish
#define Cmd_sys_hello                                  gecko_cmd_system_hello
#define Cmd_sys_reset                                  gecko_cmd_system_reset
#define Cmd_sys_get_bt_addr                            gecko_cmd_system_get_bt_address
#define Cmd_sys_set_bt_addr                            gecko_cmd_system_set_bt_address
#define Cmd_sys_set_tx_power                           gecko_cmd_system_set_tx_power
#define Cmd_sys_get_random_data                        gecko_cmd_system_get_random_data
#define Cmd_sys_halt                                   gecko_cmd_system_halt
#define Cmd_sys_set_device_name                        gecko_cmd_system_set_device_name
#define Cmd_sys_linklayer_configure                    gecko_cmd_system_linklayer_configure
#define Cmd_sys_get_counters                           gecko_cmd_system_get_counters
#define Cmd_sys_data_buffer_write                      gecko_cmd_system_data_buffer_write
#define Cmd_sys_set_identity_addr                      gecko_cmd_system_set_identity_address
#define Cmd_sys_data_buffer_clear                      gecko_cmd_system_data_buffer_clear
#define Cmd_gap_open                                   gecko_cmd_le_gap_open
#define Cmd_gap_set_mode                               gecko_cmd_le_gap_set_mode
#define Cmd_gap_discover                               gecko_cmd_le_gap_discover
#define Cmd_gap_end_procedure                          gecko_cmd_le_gap_end_procedure
#define Cmd_gap_set_adv_parameters                     gecko_cmd_le_gap_set_adv_parameters
#define Cmd_gap_set_conn_parameters                    gecko_cmd_le_gap_set_conn_parameters
#define Cmd_gap_set_scan_parameters                    gecko_cmd_le_gap_set_scan_parameters
#define Cmd_gap_set_adv_data                           gecko_cmd_le_gap_set_adv_data
#define Cmd_gap_set_adv_timeout                        gecko_cmd_le_gap_set_adv_timeout
#define Cmd_gap_bt5_set_mode                           gecko_cmd_le_gap_bt5_set_mode
#define Cmd_gap_bt5_set_adv_parameters                 gecko_cmd_le_gap_bt5_set_adv_parameters
#define Cmd_gap_bt5_set_adv_data                       gecko_cmd_le_gap_bt5_set_adv_data
#define Cmd_gap_set_privacy_mode                       gecko_cmd_le_gap_set_privacy_mode
#define Cmd_gap_set_advertise_timing                   gecko_cmd_le_gap_set_advertise_timing
#define Cmd_gap_set_advertise_channel_map              gecko_cmd_le_gap_set_advertise_channel_map
#define Cmd_gap_set_advertise_report_scan_req          gecko_cmd_le_gap_set_advertise_report_scan_request
#define Cmd_gap_set_advertise_phy                      gecko_cmd_le_gap_set_advertise_phy
#define Cmd_gap_set_advertise_config                   gecko_cmd_le_gap_set_advertise_configuration
#define Cmd_gap_clear_advertise_config                 gecko_cmd_le_gap_clear_advertise_configuration
#define Cmd_gap_start_advertising                      gecko_cmd_le_gap_start_advertising
#define Cmd_gap_stop_advertising                       gecko_cmd_le_gap_stop_advertising
#define Cmd_gap_set_discovery_timing                   gecko_cmd_le_gap_set_discovery_timing
#define Cmd_gap_set_discovery_type                     gecko_cmd_le_gap_set_discovery_type
#define Cmd_gap_start_discovery                        gecko_cmd_le_gap_start_discovery
#define Cmd_gap_set_data_channel_classification        gecko_cmd_le_gap_set_data_channel_classification
#define Cmd_gap_connect                                gecko_cmd_le_gap_connect
#define Cmd_gap_set_advertise_tx_power                 gecko_cmd_le_gap_set_advertise_tx_power
#define Cmd_gap_set_discovery_extended_scan_resp       gecko_cmd_le_gap_set_discovery_extended_scan_response
#define Cmd_gap_start_periodic_advertising             gecko_cmd_le_gap_start_periodic_advertising
#define Cmd_gap_stop_periodic_advertising              gecko_cmd_le_gap_stop_periodic_advertising
#define Cmd_gap_set_long_advertising_data              gecko_cmd_le_gap_set_long_advertising_data
#define Cmd_gap_enable_whitelisting                    gecko_cmd_le_gap_enable_whitelisting
#define Cmd_gap_set_conn_timing_parameters             gecko_cmd_le_gap_set_conn_timing_parameters
#define Cmd_sync_open                                  gecko_cmd_sync_open
#define Cmd_sync_close                                 gecko_cmd_sync_close
#define Cmd_connect_set_parameters                     gecko_cmd_le_connection_set_parameters
#define Cmd_connect_get_rssi                           gecko_cmd_le_connection_get_rssi
#define Cmd_connect_disable_slave_latency              gecko_cmd_le_connection_disable_slave_latency
#define Cmd_connect_set_phy                            gecko_cmd_le_connection_set_phy
#define Cmd_connect_close                              gecko_cmd_le_connection_close
#define Cmd_connect_set_timing_parameters              gecko_cmd_le_connection_set_timing_parameters
#define Cmd_gatt_set_max_mtu                           gecko_cmd_gatt_set_max_mtu
#define Cmd_gatt_discover_primary_services             gecko_cmd_gatt_discover_primary_services
#define Cmd_gatt_discover_primary_services_by_uuid     gecko_cmd_gatt_discover_primary_services_by_uuid
#define Cmd_gatt_discover_characts                     gecko_cmd_gatt_discover_characteristics
#define Cmd_gatt_discover_characts_by_uuid             gecko_cmd_gatt_discover_characteristics_by_uuid
#define Cmd_gatt_set_charact_notification              gecko_cmd_gatt_set_characteristic_notification
#define Cmd_gatt_discover_descriptors                  gecko_cmd_gatt_discover_descriptors
#define Cmd_gatt_read_charact_value                    gecko_cmd_gatt_read_characteristic_value
#define Cmd_gatt_read_charact_value_by_uuid            gecko_cmd_gatt_read_characteristic_value_by_uuid
#define Cmd_gatt_write_charact_value                   gecko_cmd_gatt_write_characteristic_value
#define Cmd_gatt_write_charact_value_without_resp      gecko_cmd_gatt_write_characteristic_value_without_response
#define Cmd_gatt_prepare_charact_value_write           gecko_cmd_gatt_prepare_characteristic_value_write
#define Cmd_gatt_execute_charact_value_write           gecko_cmd_gatt_execute_characteristic_value_write
#define Cmd_gatt_send_charact_confirmation             gecko_cmd_gatt_send_characteristic_confirmation
#define Cmd_gatt_read_descriptor_value                 gecko_cmd_gatt_read_descriptor_value
#define Cmd_gatt_write_descriptor_value                gecko_cmd_gatt_write_descriptor_value
#define Cmd_gatt_find_included_services                gecko_cmd_gatt_find_included_services
#define Cmd_gatt_read_multiple_charact_values          gecko_cmd_gatt_read_multiple_characteristic_values
#define Cmd_gatt_read_charact_value_from_offset        gecko_cmd_gatt_read_characteristic_value_from_offset
#define Cmd_gatt_prepare_charact_value_reliable_write  gecko_cmd_gatt_prepare_characteristic_value_reliable_write
#define Cmd_gatt_server_read_attri_value               gecko_cmd_gatt_server_read_attribute_value
#define Cmd_gatt_server_read_attri_type                gecko_cmd_gatt_server_read_attribute_type
#define Cmd_gatt_server_write_attri_value              gecko_cmd_gatt_server_write_attribute_value
#define Cmd_gatt_server_send_user_read_resp            gecko_cmd_gatt_server_send_user_read_response
#define Cmd_gatt_server_send_user_write_resp           gecko_cmd_gatt_server_send_user_write_response
#define Cmd_gatt_server_send_charact_notification      gecko_cmd_gatt_server_send_characteristic_notification
#define Cmd_gatt_server_find_attri                     gecko_cmd_gatt_server_find_attribute
#define Cmd_gatt_server_set_capabilities               gecko_cmd_gatt_server_set_capabilities
#define Cmd_gatt_server_set_max_mtu                    gecko_cmd_gatt_server_set_max_mtu
#define Cmd_set_soft_timer                             gecko_cmd_hardware_set_soft_timer
#define Cmd_hardware_get_time                          gecko_cmd_hardware_get_time
#define Cmd_hardware_set_lazy_soft_timer               gecko_cmd_hardware_set_lazy_soft_timer
#define Cmd_flash_ps_erase_all                         gecko_cmd_flash_ps_erase_all
#define Cmd_flash_ps_save                              gecko_cmd_flash_ps_save
#define Cmd_flash_ps_load                              gecko_cmd_flash_ps_load
#define Cmd_flash_ps_erase                             gecko_cmd_flash_ps_erase
#define Cmd_test_dtm_tx                                gecko_cmd_test_dtm_tx
#define Cmd_test_dtm_rx                                gecko_cmd_test_dtm_rx
#define Cmd_test_dtm_end                               gecko_cmd_test_dtm_end
#define Cmd_sm_set_bondable_mode                       gecko_cmd_sm_set_bondable_mode
#define Cmd_sm_configure                               gecko_cmd_sm_configure
#define Cmd_sm_store_bonding_config                    gecko_cmd_sm_store_bonding_configuration
#define Cmd_sm_increase_security                       gecko_cmd_sm_increase_security
#define Cmd_sm_delete_bonding                          gecko_cmd_sm_delete_bonding
#define Cmd_sm_delete_bondings                         gecko_cmd_sm_delete_bondings
#define Cmd_sm_enter_passkey                           gecko_cmd_sm_enter_passkey
#define Cmd_sm_passkey_confirm                         gecko_cmd_sm_passkey_confirm
#define Cmd_sm_set_oob_data                            gecko_cmd_sm_set_oob_data
#define Cmd_sm_list_all_bondings                       gecko_cmd_sm_list_all_bondings
#define Cmd_sm_bonding_confirm                         gecko_cmd_sm_bonding_confirm
#define Cmd_sm_set_debug_mode                          gecko_cmd_sm_set_debug_mode
#define Cmd_sm_set_passkey                             gecko_cmd_sm_set_passkey
#define Cmd_sm_use_sc_oob                              gecko_cmd_sm_use_sc_oob
#define Cmd_sm_set_sc_remote_oob_data                  gecko_cmd_sm_set_sc_remote_oob_data
#define Cmd_sm_add_to_whitelist                        gecko_cmd_sm_add_to_whitelist
#define Cmd_sm_set_minimum_key_size                    gecko_cmd_sm_set_minimum_key_size
#define Cmd_hk_configure                               gecko_cmd_homekit_configure
#define Cmd_hk_advertise                               gecko_cmd_homekit_advertise
#define Cmd_hk_delete_pairings                         gecko_cmd_homekit_delete_pairings
#define Cmd_hk_check_authcp                            gecko_cmd_homekit_check_authcp
#define Cmd_hk_get_pairing_id                          gecko_cmd_homekit_get_pairing_id
#define Cmd_hk_send_write_resp                         gecko_cmd_homekit_send_write_response
#define Cmd_hk_send_read_resp                          gecko_cmd_homekit_send_read_response
#define Cmd_hk_gsn_action                              gecko_cmd_homekit_gsn_action
#define Cmd_hk_event_notification                      gecko_cmd_homekit_event_notification
#define Cmd_hk_broadcast_action                        gecko_cmd_homekit_broadcast_action
#define Cmd_mn_init                                    gecko_cmd_mesh_node_init
#define Cmd_mn_start_unprov_beaconing                  gecko_cmd_mesh_node_start_unprov_beaconing
#define Cmd_mn_input_oob_req_rsp                       gecko_cmd_mesh_node_input_oob_request_rsp
#define Cmd_mn_get_uuid                                gecko_cmd_mesh_node_get_uuid
#define Cmd_mn_set_provisioning_data                   gecko_cmd_mesh_node_set_provisioning_data
#define Cmd_mn_init_oob                                gecko_cmd_mesh_node_init_oob
#define Cmd_mn_set_ivrecovery_mode                     gecko_cmd_mesh_node_set_ivrecovery_mode
#define Cmd_mn_get_ivrecovery_mode                     gecko_cmd_mesh_node_get_ivrecovery_mode
#define Cmd_mn_set_adv_event_filter                    gecko_cmd_mesh_node_set_adv_event_filter
#define Cmd_mn_get_statistics                          gecko_cmd_mesh_node_get_statistics
#define Cmd_mn_clear_statistics                        gecko_cmd_mesh_node_clear_statistics
#define Cmd_mn_set_net_relay_delay                     gecko_cmd_mesh_node_set_net_relay_delay
#define Cmd_mn_get_net_relay_delay                     gecko_cmd_mesh_node_get_net_relay_delay
#define Cmd_mn_get_ivupdate_state                      gecko_cmd_mesh_node_get_ivupdate_state
#define Cmd_mn_req_ivupdate                            gecko_cmd_mesh_node_request_ivupdate
#define Cmd_mn_get_seq_remaining                       gecko_cmd_mesh_node_get_seq_remaining
#define Cmd_mn_save_replay_protection_list             gecko_cmd_mesh_node_save_replay_protection_list
#define Cmd_mn_set_uuid                                gecko_cmd_mesh_node_set_uuid
#define Cmd_mn_get_element_addr                        gecko_cmd_mesh_node_get_element_address
#define Cmd_mn_static_oob_req_rsp                      gecko_cmd_mesh_node_static_oob_request_rsp
#define Cmd_mn_reset                                   gecko_cmd_mesh_node_reset

#define Cmd_mn_set_beacon_reporting                    gecko_cmd_mesh_node_set_beacon_reporting

#define Cmd_mp_init                                    gecko_cmd_mesh_prov_init
#define Cmd_mp_scan_unprov_beacons                     gecko_cmd_mesh_prov_scan_unprov_beacons
#define Cmd_mp_prov_device                             gecko_cmd_mesh_prov_provision_device
#define Cmd_mp_create_network                          gecko_cmd_mesh_prov_create_network
#define Cmd_mp_get_dcd                                 gecko_cmd_mesh_prov_get_dcd
#define Cmd_mp_get_config                              gecko_cmd_mesh_prov_get_config
#define Cmd_mp_set_config                              gecko_cmd_mesh_prov_set_config
#define Cmd_mp_create_appkey                           gecko_cmd_mesh_prov_create_appkey
#define Cmd_mp_oob_pkey_rsp                            gecko_cmd_mesh_prov_oob_pkey_rsp
#define Cmd_mp_oob_auth_rsp                            gecko_cmd_mesh_prov_oob_auth_rsp
#define Cmd_mp_set_oob_requirements                    gecko_cmd_mesh_prov_set_oob_requirements
#define Cmd_mp_key_refresh_start                       gecko_cmd_mesh_prov_key_refresh_start
#define Cmd_mp_get_key_refresh_blacklist               gecko_cmd_mesh_prov_get_key_refresh_blacklist
#define Cmd_mp_set_key_refresh_blacklist               gecko_cmd_mesh_prov_set_key_refresh_blacklist
#define Cmd_mp_appkey_add                              gecko_cmd_mesh_prov_appkey_add
#define Cmd_mp_appkey_delete                           gecko_cmd_mesh_prov_appkey_delete
#define Cmd_mp_model_app_bind                          gecko_cmd_mesh_prov_model_app_bind
#define Cmd_mp_model_app_unbind                        gecko_cmd_mesh_prov_model_app_unbind
#define Cmd_mp_model_app_get                           gecko_cmd_mesh_prov_model_app_get
#define Cmd_mp_model_sub_add                           gecko_cmd_mesh_prov_model_sub_add
#define Cmd_mp_model_pub_set                           gecko_cmd_mesh_prov_model_pub_set
#define Cmd_mp_prov_gatt_device                        gecko_cmd_mesh_prov_provision_gatt_device
#define Cmd_mp_ddb_get                                 gecko_cmd_mesh_prov_ddb_get
#define Cmd_mp_ddb_delete                              gecko_cmd_mesh_prov_ddb_delete
#define Cmd_mp_ddb_add                                 gecko_cmd_mesh_prov_ddb_add
#define Cmd_mp_ddb_list_devices                        gecko_cmd_mesh_prov_ddb_list_devices
#define Cmd_mp_network_add                             gecko_cmd_mesh_prov_network_add
#define Cmd_mp_network_delete                          gecko_cmd_mesh_prov_network_delete
#define Cmd_mp_nettx_get                               gecko_cmd_mesh_prov_nettx_get
#define Cmd_mp_nettx_set                               gecko_cmd_mesh_prov_nettx_set
#define Cmd_mp_model_sub_del                           gecko_cmd_mesh_prov_model_sub_del
#define Cmd_mp_model_sub_add_va                        gecko_cmd_mesh_prov_model_sub_add_va
#define Cmd_mp_model_sub_del_va                        gecko_cmd_mesh_prov_model_sub_del_va
#define Cmd_mp_model_sub_set                           gecko_cmd_mesh_prov_model_sub_set
#define Cmd_mp_model_sub_set_va                        gecko_cmd_mesh_prov_model_sub_set_va
#define Cmd_mp_heartbeat_pub_get                       gecko_cmd_mesh_prov_heartbeat_publication_get
#define Cmd_mp_heartbeat_pub_set                       gecko_cmd_mesh_prov_heartbeat_publication_set
#define Cmd_mp_heartbeat_sub_get                       gecko_cmd_mesh_prov_heartbeat_subscription_get
#define Cmd_mp_heartbeat_sub_set                       gecko_cmd_mesh_prov_heartbeat_subscription_set
#define Cmd_mp_relay_get                               gecko_cmd_mesh_prov_relay_get
#define Cmd_mp_relay_set                               gecko_cmd_mesh_prov_relay_set
#define Cmd_mp_reset_node                              gecko_cmd_mesh_prov_reset_node
#define Cmd_mp_appkey_get                              gecko_cmd_mesh_prov_appkey_get
#define Cmd_mp_network_get                             gecko_cmd_mesh_prov_network_get
#define Cmd_mp_model_sub_clear                         gecko_cmd_mesh_prov_model_sub_clear
#define Cmd_mp_model_pub_get                           gecko_cmd_mesh_prov_model_pub_get
#define Cmd_mp_model_pub_set_va                        gecko_cmd_mesh_prov_model_pub_set_va
#define Cmd_mp_model_pub_set_cred                      gecko_cmd_mesh_prov_model_pub_set_cred
#define Cmd_mp_model_pub_set_va_cred                   gecko_cmd_mesh_prov_model_pub_set_va_cred
#define Cmd_mp_model_sub_get                           gecko_cmd_mesh_prov_model_sub_get
#define Cmd_mp_friend_timeout_get                      gecko_cmd_mesh_prov_friend_timeout_get
#define Cmd_mp_get_default_config_timeout              gecko_cmd_mesh_prov_get_default_configuration_timeout
#define Cmd_mp_set_default_config_timeout              gecko_cmd_mesh_prov_set_default_configuration_timeout
#define Cmd_mp_prov_device_with_addr                   gecko_cmd_mesh_prov_provision_device_with_address
#define Cmd_mp_prov_gatt_device_with_addr              gecko_cmd_mesh_prov_provision_gatt_device_with_address
#define Cmd_mp_initialize_network                      gecko_cmd_mesh_prov_initialize_network
#define Cmd_mp_get_key_refresh_appkey_blacklist        gecko_cmd_mesh_prov_get_key_refresh_appkey_blacklist
#define Cmd_mp_set_key_refresh_appkey_blacklist        gecko_cmd_mesh_prov_set_key_refresh_appkey_blacklist
#define Cmd_mp_stop_scan_unprov_beacons                gecko_cmd_mesh_prov_stop_scan_unprov_beacons
#define Cmd_m_proxy_connect                            gecko_cmd_mesh_proxy_connect
#define Cmd_m_proxy_disconnect                         gecko_cmd_mesh_proxy_disconnect
#define Cmd_m_proxy_set_filter_type                    gecko_cmd_mesh_proxy_set_filter_type
#define Cmd_m_proxy_allow                              gecko_cmd_mesh_proxy_allow
#define Cmd_m_proxy_deny                               gecko_cmd_mesh_proxy_deny
#define Cmd_mv_model_send                              gecko_cmd_mesh_vendor_model_send
#define Cmd_mv_model_set_pub                           gecko_cmd_mesh_vendor_model_set_publication
#define Cmd_mv_model_clear_pub                         gecko_cmd_mesh_vendor_model_clear_publication
#define Cmd_mv_model_publish                           gecko_cmd_mesh_vendor_model_publish
#define Cmd_mv_model_init                              gecko_cmd_mesh_vendor_model_init
#define Cmd_mv_model_deinit                            gecko_cmd_mesh_vendor_model_deinit
#define Cmd_mh_client_get                              gecko_cmd_mesh_health_client_get
#define Cmd_mh_client_clear                            gecko_cmd_mesh_health_client_clear
#define Cmd_mh_client_test                             gecko_cmd_mesh_health_client_test
#define Cmd_mh_client_get_period                       gecko_cmd_mesh_health_client_get_period
#define Cmd_mh_client_set_period                       gecko_cmd_mesh_health_client_set_period
#define Cmd_mh_client_get_attention                    gecko_cmd_mesh_health_client_get_attention
#define Cmd_mh_client_set_attention                    gecko_cmd_mesh_health_client_set_attention
#define Cmd_mh_server_set_fault                        gecko_cmd_mesh_health_server_set_fault
#define Cmd_mh_server_clear_fault                      gecko_cmd_mesh_health_server_clear_fault
#define Cmd_mh_server_test_resp                        gecko_cmd_mesh_health_server_test_response
#define Cmd_mg_client_get                              gecko_cmd_mesh_generic_client_get
#define Cmd_mg_client_set                              gecko_cmd_mesh_generic_client_set
#define Cmd_mg_client_publish                          gecko_cmd_mesh_generic_client_publish
#define Cmd_mg_client_get_params                       gecko_cmd_mesh_generic_client_get_params
#define Cmd_mg_client_init                             gecko_cmd_mesh_generic_client_init
#define Cmd_mg_server_resp                             gecko_cmd_mesh_generic_server_response
#define Cmd_mg_server_update                           gecko_cmd_mesh_generic_server_update
#define Cmd_mg_server_publish                          gecko_cmd_mesh_generic_server_publish
#define Cmd_mg_server_init                             gecko_cmd_mesh_generic_server_init
#define Cmd_coex_set_options                           gecko_cmd_coex_set_options
#define Cmd_coex_get_counters                          gecko_cmd_coex_get_counters
#define Cmd_mt_get_nettx                               gecko_cmd_mesh_test_get_nettx
#define Cmd_mt_set_nettx                               gecko_cmd_mesh_test_set_nettx
#define Cmd_mt_get_relay                               gecko_cmd_mesh_test_get_relay
#define Cmd_mt_set_relay                               gecko_cmd_mesh_test_set_relay
#define Cmd_mt_set_adv_scan_params                     gecko_cmd_mesh_test_set_adv_scan_params
#define Cmd_mt_set_ivupdate_test_mode                  gecko_cmd_mesh_test_set_ivupdate_test_mode
#define Cmd_mt_get_ivupdate_test_mode                  gecko_cmd_mesh_test_get_ivupdate_test_mode
#define Cmd_mt_set_segment_send_delay                  gecko_cmd_mesh_test_set_segment_send_delay
#define Cmd_mt_set_ivupdate_state                      gecko_cmd_mesh_test_set_ivupdate_state
#define Cmd_mt_send_beacons                            gecko_cmd_mesh_test_send_beacons

#define Cmd_mt_bind_local_model_app                    gecko_cmd_mesh_test_bind_local_model_app
#define Cmd_mt_unbind_local_model_app                  gecko_cmd_mesh_test_unbind_local_model_app
#define Cmd_mt_add_local_model_sub                     gecko_cmd_mesh_test_add_local_model_sub
#define Cmd_mt_del_local_model_sub                     gecko_cmd_mesh_test_del_local_model_sub
#define Cmd_mt_add_local_model_sub_va                  gecko_cmd_mesh_test_add_local_model_sub_va
#define Cmd_mt_del_local_model_sub_va                  gecko_cmd_mesh_test_del_local_model_sub_va
#define Cmd_mt_get_local_model_sub                     gecko_cmd_mesh_test_get_local_model_sub
#define Cmd_mt_set_local_model_pub                     gecko_cmd_mesh_test_set_local_model_pub
#define Cmd_mt_set_local_model_pub_va                  gecko_cmd_mesh_test_set_local_model_pub_va
#define Cmd_mt_get_local_model_pub                     gecko_cmd_mesh_test_get_local_model_pub
#define Cmd_mt_set_local_heartbeat_sub                 gecko_cmd_mesh_test_set_local_heartbeat_subscription
#define Cmd_mt_get_local_heartbeat_sub                 gecko_cmd_mesh_test_get_local_heartbeat_subscription
#define Cmd_mt_get_local_heartbeat_pub                 gecko_cmd_mesh_test_get_local_heartbeat_publication
#define Cmd_mt_set_local_heartbeat_pub                 gecko_cmd_mesh_test_set_local_heartbeat_publication
#define Cmd_mt_set_local_config                        gecko_cmd_mesh_test_set_local_config
#define Cmd_mt_get_local_config                        gecko_cmd_mesh_test_get_local_config
#define Cmd_mt_add_local_key                           gecko_cmd_mesh_test_add_local_key
#define Cmd_mt_del_local_key                           gecko_cmd_mesh_test_del_local_key
#define Cmd_mt_update_local_key                        gecko_cmd_mesh_test_update_local_key
#define Cmd_mt_set_sar_config                          gecko_cmd_mesh_test_set_sar_config
#define Cmd_mt_get_element_seqnum                      gecko_cmd_mesh_test_get_element_seqnum
#define Cmd_mt_set_adv_bearer_state                    gecko_cmd_mesh_test_set_adv_bearer_state
#define Cmd_mt_get_key_count                           gecko_cmd_mesh_test_get_key_count
#define Cmd_mt_get_key                                 gecko_cmd_mesh_test_get_key
#define Cmd_mt_prov_get_device_key                     gecko_cmd_mesh_test_prov_get_device_key
#define Cmd_mt_prov_prepare_key_refresh                gecko_cmd_mesh_test_prov_prepare_key_refresh
#define Cmd_mt_cancel_segmented_tx                     gecko_cmd_mesh_test_cancel_segmented_tx
#define Cmd_mt_set_iv_index                            gecko_cmd_mesh_test_set_iv_index
#define Cmd_mt_set_element_seqnum                      gecko_cmd_mesh_test_set_element_seqnum
#define Cmd_m_lpn_init                                 gecko_cmd_mesh_lpn_init
#define Cmd_m_lpn_deinit                               gecko_cmd_mesh_lpn_deinit
#define Cmd_m_lpn_configure                            gecko_cmd_mesh_lpn_configure
#define Cmd_m_lpn_establish_friendship                 gecko_cmd_mesh_lpn_establish_friendship
#define Cmd_m_lpn_poll                                 gecko_cmd_mesh_lpn_poll
#define Cmd_m_lpn_terminate_friendship                 gecko_cmd_mesh_lpn_terminate_friendship
#define Cmd_m_lpn_config                               gecko_cmd_mesh_lpn_config
#define Cmd_m_friend_init                              gecko_cmd_mesh_friend_init
#define Cmd_m_friend_deinit                            gecko_cmd_mesh_friend_deinit
#define Cmd_mc_client_cancel_req                       gecko_cmd_mesh_config_client_cancel_request
#define Cmd_mc_client_get_req_status                   gecko_cmd_mesh_config_client_get_request_status
#define Cmd_mc_client_get_default_timeout              gecko_cmd_mesh_config_client_get_default_timeout
#define Cmd_mc_client_set_default_timeout              gecko_cmd_mesh_config_client_set_default_timeout
#define Cmd_mc_client_add_netkey                       gecko_cmd_mesh_config_client_add_netkey
#define Cmd_mc_client_remove_netkey                    gecko_cmd_mesh_config_client_remove_netkey
#define Cmd_mc_client_list_netkeys                     gecko_cmd_mesh_config_client_list_netkeys
#define Cmd_mc_client_add_appkey                       gecko_cmd_mesh_config_client_add_appkey
#define Cmd_mc_client_remove_appkey                    gecko_cmd_mesh_config_client_remove_appkey
#define Cmd_mc_client_list_appkeys                     gecko_cmd_mesh_config_client_list_appkeys
#define Cmd_mc_client_bind_model                       gecko_cmd_mesh_config_client_bind_model
#define Cmd_mc_client_unbind_model                     gecko_cmd_mesh_config_client_unbind_model
#define Cmd_mc_client_list_bindings                    gecko_cmd_mesh_config_client_list_bindings
#define Cmd_mc_client_get_model_pub                    gecko_cmd_mesh_config_client_get_model_pub
#define Cmd_mc_client_set_model_pub                    gecko_cmd_mesh_config_client_set_model_pub
#define Cmd_mc_client_set_model_pub_va                 gecko_cmd_mesh_config_client_set_model_pub_va
#define Cmd_mc_client_add_model_sub                    gecko_cmd_mesh_config_client_add_model_sub
#define Cmd_mc_client_add_model_sub_va                 gecko_cmd_mesh_config_client_add_model_sub_va
#define Cmd_mc_client_remove_model_sub                 gecko_cmd_mesh_config_client_remove_model_sub
#define Cmd_mc_client_remove_model_sub_va              gecko_cmd_mesh_config_client_remove_model_sub_va
#define Cmd_mc_client_set_model_sub                    gecko_cmd_mesh_config_client_set_model_sub
#define Cmd_mc_client_set_model_sub_va                 gecko_cmd_mesh_config_client_set_model_sub_va
#define Cmd_mc_client_clear_model_sub                  gecko_cmd_mesh_config_client_clear_model_sub
#define Cmd_mc_client_list_subs                        gecko_cmd_mesh_config_client_list_subs
#define Cmd_mc_client_get_heartbeat_pub                gecko_cmd_mesh_config_client_get_heartbeat_pub
#define Cmd_mc_client_set_heartbeat_pub                gecko_cmd_mesh_config_client_set_heartbeat_pub
#define Cmd_mc_client_get_heartbeat_sub                gecko_cmd_mesh_config_client_get_heartbeat_sub
#define Cmd_mc_client_set_heartbeat_sub                gecko_cmd_mesh_config_client_set_heartbeat_sub
#define Cmd_mc_client_get_beacon                       gecko_cmd_mesh_config_client_get_beacon
#define Cmd_mc_client_set_beacon                       gecko_cmd_mesh_config_client_set_beacon
#define Cmd_mc_client_get_default_ttl                  gecko_cmd_mesh_config_client_get_default_ttl
#define Cmd_mc_client_set_default_ttl                  gecko_cmd_mesh_config_client_set_default_ttl
#define Cmd_mc_client_get_gatt_proxy                   gecko_cmd_mesh_config_client_get_gatt_proxy
#define Cmd_mc_client_set_gatt_proxy                   gecko_cmd_mesh_config_client_set_gatt_proxy
#define Cmd_mc_client_get_relay                        gecko_cmd_mesh_config_client_get_relay
#define Cmd_mc_client_set_relay                        gecko_cmd_mesh_config_client_set_relay
#define Cmd_mc_client_get_network_transmit             gecko_cmd_mesh_config_client_get_network_transmit
#define Cmd_mc_client_set_network_transmit             gecko_cmd_mesh_config_client_set_network_transmit
#define Cmd_mc_client_get_identity                     gecko_cmd_mesh_config_client_get_identity
#define Cmd_mc_client_set_identity                     gecko_cmd_mesh_config_client_set_identity
#define Cmd_mc_client_get_friend                       gecko_cmd_mesh_config_client_get_friend
#define Cmd_mc_client_set_friend                       gecko_cmd_mesh_config_client_set_friend
#define Cmd_mc_client_get_lpn_polltimeout              gecko_cmd_mesh_config_client_get_lpn_polltimeout
#define Cmd_mc_client_get_dcd                          gecko_cmd_mesh_config_client_get_dcd
#define Cmd_mc_client_reset_node                       gecko_cmd_mesh_config_client_reset_node
#define Cmd_l2cap_coc_send_connect_req                 gecko_cmd_l2cap_coc_send_connection_request
#define Cmd_l2cap_coc_send_connect_resp                gecko_cmd_l2cap_coc_send_connection_response
#define Cmd_l2cap_coc_send_le_flow_control_credit      gecko_cmd_l2cap_coc_send_le_flow_control_credit
#define Cmd_l2cap_coc_send_disconnect_req              gecko_cmd_l2cap_coc_send_disconnection_request
#define Cmd_l2cap_coc_send_data                        gecko_cmd_l2cap_coc_send_data
#define Cmd_cte_transmitter_enable_cte_resp            gecko_cmd_cte_transmitter_enable_cte_response
#define Cmd_cte_transmitter_disable_cte_resp           gecko_cmd_cte_transmitter_disable_cte_response
#define Cmd_cte_transmitter_start_connectless_cte      gecko_cmd_cte_transmitter_start_connectionless_cte
#define Cmd_cte_transmitter_stop_connectless_cte       gecko_cmd_cte_transmitter_stop_connectionless_cte
#define Cmd_cte_transmitter_set_dtm_parameters         gecko_cmd_cte_transmitter_set_dtm_parameters
#define Cmd_cte_transmitter_clear_dtm_parameters       gecko_cmd_cte_transmitter_clear_dtm_parameters
#define Cmd_cte_receiver_configure                     gecko_cmd_cte_receiver_configure
#define Cmd_cte_receiver_start_iq_sampling             gecko_cmd_cte_receiver_start_iq_sampling
#define Cmd_cte_receiver_stop_iq_sampling              gecko_cmd_cte_receiver_stop_iq_sampling
#define Cmd_cte_receiver_start_connectless_iq_sampling gecko_cmd_cte_receiver_start_connectionless_iq_sampling
#define Cmd_cte_receiver_stop_connectless_iq_sampling  gecko_cmd_cte_receiver_stop_connectionless_iq_sampling
#define Cmd_cte_receiver_set_dtm_parameters            gecko_cmd_cte_receiver_set_dtm_parameters
#define Cmd_cte_receiver_clear_dtm_parameters          gecko_cmd_cte_receiver_clear_dtm_parameters
#define Cmd_ms_server_init                             gecko_cmd_mesh_sensor_server_init
#define Cmd_ms_server_deinit                           gecko_cmd_mesh_sensor_server_deinit
#define Cmd_ms_server_send_descriptor_status           gecko_cmd_mesh_sensor_server_send_descriptor_status
#define Cmd_ms_server_send_status                      gecko_cmd_mesh_sensor_server_send_status
#define Cmd_ms_server_send_column_status               gecko_cmd_mesh_sensor_server_send_column_status
#define Cmd_ms_server_send_series_status               gecko_cmd_mesh_sensor_server_send_series_status
#define Cmd_ms_setup_server_send_cadence_status        gecko_cmd_mesh_sensor_setup_server_send_cadence_status
#define Cmd_ms_setup_server_send_settings_status       gecko_cmd_mesh_sensor_setup_server_send_settings_status
#define Cmd_ms_setup_server_send_setting_status        gecko_cmd_mesh_sensor_setup_server_send_setting_status
#define Cmd_ms_client_init                             gecko_cmd_mesh_sensor_client_init
#define Cmd_ms_client_deinit                           gecko_cmd_mesh_sensor_client_deinit
#define Cmd_ms_client_get_descriptor                   gecko_cmd_mesh_sensor_client_get_descriptor
#define Cmd_ms_client_get                              gecko_cmd_mesh_sensor_client_get
#define Cmd_ms_client_get_column                       gecko_cmd_mesh_sensor_client_get_column
#define Cmd_ms_client_get_series                       gecko_cmd_mesh_sensor_client_get_series
#define Cmd_ms_client_get_cadence                      gecko_cmd_mesh_sensor_client_get_cadence
#define Cmd_ms_client_set_cadence                      gecko_cmd_mesh_sensor_client_set_cadence
#define Cmd_ms_client_get_settings                     gecko_cmd_mesh_sensor_client_get_settings
#define Cmd_ms_client_get_setting                      gecko_cmd_mesh_sensor_client_get_setting
#define Cmd_ms_client_set_setting                      gecko_cmd_mesh_sensor_client_set_setting

//RSP event
#define Rsp_dfu_flash_set_addr                         gecko_rsp_dfu_flash_set_address_id
#define Rsp_dfu_flash_upload                           gecko_rsp_dfu_flash_upload_id
#define Rsp_dfu_flash_upload_finish                    gecko_rsp_dfu_flash_upload_finish_id
#define Rsp_sys_hello                                  gecko_rsp_system_hello_id
#define Rsp_sys_get_bt_addr                            gecko_rsp_system_get_bt_address_id
#define Rsp_sys_set_bt_addr                            gecko_rsp_system_set_bt_address_id
#define Rsp_sys_set_tx_power                           gecko_rsp_system_set_tx_power_id
#define Rsp_sys_get_random_data                        gecko_rsp_system_get_random_data_id
#define Rsp_sys_halt                                   gecko_rsp_system_halt_id
#define Rsp_sys_set_device_name                        gecko_rsp_system_set_device_name_id
#define Rsp_sys_linklayer_configure                    gecko_rsp_system_linklayer_configure_id
#define Rsp_sys_get_counters                           gecko_rsp_system_get_counters_id
#define Rsp_sys_data_buffer_write                      gecko_rsp_system_data_buffer_write_id
#define Rsp_sys_set_identity_addr                      gecko_rsp_system_set_identity_address_id
#define Rsp_sys_data_buffer_clear                      gecko_rsp_system_data_buffer_clear_id
#define Rsp_gap_open                                   gecko_rsp_le_gap_open_id
#define Rsp_gap_set_mode                               gecko_rsp_le_gap_set_mode_id
#define Rsp_gap_discover                               gecko_rsp_le_gap_discover_id
#define Rsp_gap_end_procedure                          gecko_rsp_le_gap_end_procedure_id
#define Rsp_gap_set_adv_parameters                     gecko_rsp_le_gap_set_adv_parameters_id
#define Rsp_gap_set_conn_parameters                    gecko_rsp_le_gap_set_conn_parameters_id
#define Rsp_gap_set_scan_parameters                    gecko_rsp_le_gap_set_scan_parameters_id
#define Rsp_gap_set_adv_data                           gecko_rsp_le_gap_set_adv_data_id
#define Rsp_gap_set_adv_timeout                        gecko_rsp_le_gap_set_adv_timeout_id
#define Rsp_gap_bt5_set_mode                           gecko_rsp_le_gap_bt5_set_mode_id
#define Rsp_gap_bt5_set_adv_parameters                 gecko_rsp_le_gap_bt5_set_adv_parameters_id
#define Rsp_gap_bt5_set_adv_data                       gecko_rsp_le_gap_bt5_set_adv_data_id
#define Rsp_gap_set_privacy_mode                       gecko_rsp_le_gap_set_privacy_mode_id
#define Rsp_gap_set_advertise_timing                   gecko_rsp_le_gap_set_advertise_timing_id
#define Rsp_gap_set_advertise_channel_map              gecko_rsp_le_gap_set_advertise_channel_map_id
#define Rsp_gap_set_advertise_report_scan_req          gecko_rsp_le_gap_set_advertise_report_scan_request_id
#define Rsp_gap_set_advertise_phy                      gecko_rsp_le_gap_set_advertise_phy_id
#define Rsp_gap_set_advertise_config                   gecko_rsp_le_gap_set_advertise_configuration_id
#define Rsp_gap_clear_advertise_config                 gecko_rsp_le_gap_clear_advertise_configuration_id
#define Rsp_gap_start_advertising                      gecko_rsp_le_gap_start_advertising_id
#define Rsp_gap_stop_advertising                       gecko_rsp_le_gap_stop_advertising_id
#define Rsp_gap_set_discovery_timing                   gecko_rsp_le_gap_set_discovery_timing_id
#define Rsp_gap_set_discovery_type                     gecko_rsp_le_gap_set_discovery_type_id
#define Rsp_gap_start_discovery                        gecko_rsp_le_gap_start_discovery_id
#define Rsp_gap_set_data_channel_classification        gecko_rsp_le_gap_set_data_channel_classification_id
#define Rsp_gap_connect                                gecko_rsp_le_gap_connect_id
#define Rsp_gap_set_advertise_tx_power                 gecko_rsp_le_gap_set_advertise_tx_power_id
#define Rsp_gap_set_discovery_extended_scan_resp       gecko_rsp_le_gap_set_discovery_extended_scan_response_id
#define Rsp_gap_start_periodic_advertising             gecko_rsp_le_gap_start_periodic_advertising_id
#define Rsp_gap_stop_periodic_advertising              gecko_rsp_le_gap_stop_periodic_advertising_id
#define Rsp_gap_set_long_advertising_data              gecko_rsp_le_gap_set_long_advertising_data_id
#define Rsp_gap_enable_whitelisting                    gecko_rsp_le_gap_enable_whitelisting_id
#define Rsp_gap_set_conn_timing_parameters             gecko_rsp_le_gap_set_conn_timing_parameters_id
#define Rsp_sync_open                                  gecko_rsp_sync_open_id
#define Rsp_sync_close                                 gecko_rsp_sync_close_id
#define Rsp_connect_set_parameters                     gecko_rsp_le_connection_set_parameters_id
#define Rsp_connect_get_rssi                           gecko_rsp_le_connection_get_rssi_id
#define Rsp_connect_disable_slave_latency              gecko_rsp_le_connection_disable_slave_latency_id
#define Rsp_connect_set_phy                            gecko_rsp_le_connection_set_phy_id
#define Rsp_connect_close                              gecko_rsp_le_connection_close_id
#define Rsp_connect_set_timing_parameters              gecko_rsp_le_connection_set_timing_parameters_id
#define Rsp_gatt_set_max_mtu                           gecko_rsp_gatt_set_max_mtu_id
#define Rsp_gatt_discover_primary_services             gecko_rsp_gatt_discover_primary_services_id
#define Rsp_gatt_discover_primary_services_by_uuid     gecko_rsp_gatt_discover_primary_services_by_uuid_id
#define Rsp_gatt_discover_characts                     gecko_rsp_gatt_discover_characteristics_id
#define Rsp_gatt_discover_characts_by_uuid             gecko_rsp_gatt_discover_characteristics_by_uuid_id
#define Rsp_gatt_set_charact_notification              gecko_rsp_gatt_set_characteristic_notification_id
#define Rsp_gatt_discover_descriptors                  gecko_rsp_gatt_discover_descriptors_id
#define Rsp_gatt_read_charact_value                    gecko_rsp_gatt_read_characteristic_value_id
#define Rsp_gatt_read_charact_value_by_uuid            gecko_rsp_gatt_read_characteristic_value_by_uuid_id
#define Rsp_gatt_write_charact_value                   gecko_rsp_gatt_write_characteristic_value_id
#define Rsp_gatt_write_charact_value_without_resp      gecko_rsp_gatt_write_characteristic_value_without_response_id
#define Rsp_gatt_prepare_charact_value_write           gecko_rsp_gatt_prepare_characteristic_value_write_id
#define Rsp_gatt_execute_charact_value_write           gecko_rsp_gatt_execute_characteristic_value_write_id
#define Rsp_gatt_send_charact_confirmation             gecko_rsp_gatt_send_characteristic_confirmation_id
#define Rsp_gatt_read_descriptor_value                 gecko_rsp_gatt_read_descriptor_value_id
#define Rsp_gatt_write_descriptor_value                gecko_rsp_gatt_write_descriptor_value_id
#define Rsp_gatt_find_included_services                gecko_rsp_gatt_find_included_services_id
#define Rsp_gatt_read_multiple_charact_values          gecko_rsp_gatt_read_multiple_characteristic_values_id
#define Rsp_gatt_read_charact_value_from_offset        gecko_rsp_gatt_read_characteristic_value_from_offset_id
#define Rsp_gatt_prepare_charact_value_reliable_write  gecko_rsp_gatt_prepare_characteristic_value_reliable_write_id
#define Rsp_gatt_server_read_attri_value               gecko_rsp_gatt_server_read_attribute_value_id
#define Rsp_gatt_server_read_attri_type                gecko_rsp_gatt_server_read_attribute_type_id
#define Rsp_gatt_server_write_attri_value              gecko_rsp_gatt_server_write_attribute_value_id
#define Rsp_gatt_server_send_user_read_resp            gecko_rsp_gatt_server_send_user_read_response_id
#define Rsp_gatt_server_send_user_write_resp           gecko_rsp_gatt_server_send_user_write_response_id
#define Rsp_gatt_server_send_charact_notification      gecko_rsp_gatt_server_send_characteristic_notification_id
#define Rsp_gatt_server_find_attri                     gecko_rsp_gatt_server_find_attribute_id
#define Rsp_gatt_server_set_capabilities               gecko_rsp_gatt_server_set_capabilities_id
#define Rsp_gatt_server_set_max_mtu                    gecko_rsp_gatt_server_set_max_mtu_id
#define Rsp_hardware_set_soft_timer                    gecko_rsp_hardware_set_soft_timer_id
#define Rsp_hardware_get_time                          gecko_rsp_hardware_get_time_id
#define Rsp_hardware_set_lazy_soft_timer               gecko_rsp_hardware_set_lazy_soft_timer_id
#define Rsp_flash_ps_erase_all                         gecko_rsp_flash_ps_erase_all_id
#define Rsp_flash_ps_save                              gecko_rsp_flash_ps_save_id
#define Rsp_flash_ps_load                              gecko_rsp_flash_ps_load_id
#define Rsp_flash_ps_erase                             gecko_rsp_flash_ps_erase_id
#define Rsp_test_dtm_tx                                gecko_rsp_test_dtm_tx_id
#define Rsp_test_dtm_rx                                gecko_rsp_test_dtm_rx_id
#define Rsp_test_dtm_end                               gecko_rsp_test_dtm_end_id
#define Rsp_sm_set_bondable_mode                       gecko_rsp_sm_set_bondable_mode_id
#define Rsp_sm_configure                               gecko_rsp_sm_configure_id
#define Rsp_sm_store_bonding_config                    gecko_rsp_sm_store_bonding_configuration_id
#define Rsp_sm_increase_security                       gecko_rsp_sm_increase_security_id
#define Rsp_sm_delete_bonding                          gecko_rsp_sm_delete_bonding_id
#define Rsp_sm_delete_bondings                         gecko_rsp_sm_delete_bondings_id
#define Rsp_sm_enter_passkey                           gecko_rsp_sm_enter_passkey_id
#define Rsp_sm_passkey_confirm                         gecko_rsp_sm_passkey_confirm_id
#define Rsp_sm_set_oob_data                            gecko_rsp_sm_set_oob_data_id
#define Rsp_sm_list_all_bondings                       gecko_rsp_sm_list_all_bondings_id
#define Rsp_sm_bonding_confirm                         gecko_rsp_sm_bonding_confirm_id
#define Rsp_sm_set_debug_mode                          gecko_rsp_sm_set_debug_mode_id
#define Rsp_sm_set_passkey                             gecko_rsp_sm_set_passkey_id
#define Rsp_sm_use_sc_oob                              gecko_rsp_sm_use_sc_oob_id
#define Rsp_sm_set_sc_remote_oob_data                  gecko_rsp_sm_set_sc_remote_oob_data_id
#define Rsp_sm_add_to_whitelist                        gecko_rsp_sm_add_to_whitelist_id
#define Rsp_sm_set_minimum_key_size                    gecko_rsp_sm_set_minimum_key_size_id
#define Rsp_hk_configure                               gecko_rsp_homekit_configure_id
#define Rsp_hk_advertise                               gecko_rsp_homekit_advertise_id
#define Rsp_hk_delete_pairings                         gecko_rsp_homekit_delete_pairings_id
#define Rsp_hk_check_authcp                            gecko_rsp_homekit_check_authcp_id
#define Rsp_hk_get_pairing_id                          gecko_rsp_homekit_get_pairing_id_id
#define Rsp_hk_send_write_resp                         gecko_rsp_homekit_send_write_response_id
#define Rsp_hk_send_read_resp                          gecko_rsp_homekit_send_read_response_id
#define Rsp_hk_gsn_action                              gecko_rsp_homekit_gsn_action_id
#define Rsp_hk_event_notification                      gecko_rsp_homekit_event_notification_id
#define Rsp_hk_broadcast_action                        gecko_rsp_homekit_broadcast_action_id
#define Rsp_mn_init                                    gecko_rsp_mesh_node_init_id
#define Rsp_mn_start_unprov_beaconing                  gecko_rsp_mesh_node_start_unprov_beaconing_id
#define Rsp_mn_input_oob_req_rsp                       gecko_rsp_mesh_node_input_oob_request_rsp_id
#define Rsp_mn_get_uuid                                gecko_rsp_mesh_node_get_uuid_id
#define Rsp_mn_set_provisioning_data                   gecko_rsp_mesh_node_set_provisioning_data_id
#define Rsp_mn_init_oob                                gecko_rsp_mesh_node_init_oob_id
#define Rsp_mn_set_ivrecovery_mode                     gecko_rsp_mesh_node_set_ivrecovery_mode_id
#define Rsp_mn_get_ivrecovery_mode                     gecko_rsp_mesh_node_get_ivrecovery_mode_id
#define Rsp_mn_set_adv_event_filter                    gecko_rsp_mesh_node_set_adv_event_filter_id
#define Rsp_mn_get_statistics                          gecko_rsp_mesh_node_get_statistics_id
#define Rsp_mn_clear_statistics                        gecko_rsp_mesh_node_clear_statistics_id
#define Rsp_mn_set_net_relay_delay                     gecko_rsp_mesh_node_set_net_relay_delay_id
#define Rsp_mn_get_net_relay_delay                     gecko_rsp_mesh_node_get_net_relay_delay_id
#define Rsp_mn_get_ivupdate_state                      gecko_rsp_mesh_node_get_ivupdate_state_id
#define Rsp_mn_req_ivupdate                            gecko_rsp_mesh_node_request_ivupdate_id
#define Rsp_mn_get_seq_remaining                       gecko_rsp_mesh_node_get_seq_remaining_id
#define Rsp_mn_save_replay_protection_list             gecko_rsp_mesh_node_save_replay_protection_list_id
#define Rsp_mn_set_uuid                                gecko_rsp_mesh_node_set_uuid_id
#define Rsp_mn_get_element_addr                        gecko_rsp_mesh_node_get_element_address_id
#define Rsp_mn_static_oob_req_rsp                      gecko_rsp_mesh_node_static_oob_request_rsp_id
#define Rsp_mn_reset                                   gecko_rsp_mesh_node_reset_id
#define Rsp_mp_init                                    gecko_rsp_mesh_prov_init_id
#define Rsp_mp_scan_unprov_beacons                     gecko_rsp_mesh_prov_scan_unprov_beacons_id
#define Rsp_mp_prov_device                             gecko_rsp_mesh_prov_provision_device_id
#define Rsp_mp_create_network                          gecko_rsp_mesh_prov_create_network_id
#define Rsp_mp_get_dcd                                 gecko_rsp_mesh_prov_get_dcd_id
#define Rsp_mp_get_config                              gecko_rsp_mesh_prov_get_config_id
#define Rsp_mp_set_config                              gecko_rsp_mesh_prov_set_config_id
#define Rsp_mp_create_appkey                           gecko_rsp_mesh_prov_create_appkey_id
#define Rsp_mp_oob_pkey_rsp                            gecko_rsp_mesh_prov_oob_pkey_rsp_id
#define Rsp_mp_oob_auth_rsp                            gecko_rsp_mesh_prov_oob_auth_rsp_id
#define Rsp_mp_set_oob_requirements                    gecko_rsp_mesh_prov_set_oob_requirements_id
#define Rsp_mp_key_refresh_start                       gecko_rsp_mesh_prov_key_refresh_start_id
#define Rsp_mp_get_key_refresh_blacklist               gecko_rsp_mesh_prov_get_key_refresh_blacklist_id
#define Rsp_mp_set_key_refresh_blacklist               gecko_rsp_mesh_prov_set_key_refresh_blacklist_id
#define Rsp_mp_appkey_add                              gecko_rsp_mesh_prov_appkey_add_id
#define Rsp_mp_appkey_delete                           gecko_rsp_mesh_prov_appkey_delete_id
#define Rsp_mp_model_app_bind                          gecko_rsp_mesh_prov_model_app_bind_id
#define Rsp_mp_model_app_unbind                        gecko_rsp_mesh_prov_model_app_unbind_id
#define Rsp_mp_model_app_get                           gecko_rsp_mesh_prov_model_app_get_id
#define Rsp_mp_model_sub_add                           gecko_rsp_mesh_prov_model_sub_add_id
#define Rsp_mp_model_pub_set                           gecko_rsp_mesh_prov_model_pub_set_id
#define Rsp_mp_prov_gatt_device                        gecko_rsp_mesh_prov_provision_gatt_device_id
#define Rsp_mp_ddb_get                                 gecko_rsp_mesh_prov_ddb_get_id
#define Rsp_mp_ddb_delete                              gecko_rsp_mesh_prov_ddb_delete_id
#define Rsp_mp_ddb_add                                 gecko_rsp_mesh_prov_ddb_add_id
#define Rsp_mp_ddb_list_devices                        gecko_rsp_mesh_prov_ddb_list_devices_id
#define Rsp_mp_network_add                             gecko_rsp_mesh_prov_network_add_id
#define Rsp_mp_network_delete                          gecko_rsp_mesh_prov_network_delete_id
#define Rsp_mp_nettx_get                               gecko_rsp_mesh_prov_nettx_get_id
#define Rsp_mp_nettx_set                               gecko_rsp_mesh_prov_nettx_set_id
#define Rsp_mp_model_sub_del                           gecko_rsp_mesh_prov_model_sub_del_id
#define Rsp_mp_model_sub_add_va                        gecko_rsp_mesh_prov_model_sub_add_va_id
#define Rsp_mp_model_sub_del_va                        gecko_rsp_mesh_prov_model_sub_del_va_id
#define Rsp_mp_model_sub_set                           gecko_rsp_mesh_prov_model_sub_set_id
#define Rsp_mp_model_sub_set_va                        gecko_rsp_mesh_prov_model_sub_set_va_id
#define Rsp_mp_heartbeat_pub_get                       gecko_rsp_mesh_prov_heartbeat_publication_get_id
#define Rsp_mp_heartbeat_pub_set                       gecko_rsp_mesh_prov_heartbeat_publication_set_id
#define Rsp_mp_heartbeat_sub_get                       gecko_rsp_mesh_prov_heartbeat_subscription_get_id
#define Rsp_mp_heartbeat_sub_set                       gecko_rsp_mesh_prov_heartbeat_subscription_set_id
#define Rsp_mp_relay_get                               gecko_rsp_mesh_prov_relay_get_id
#define Rsp_mp_relay_set                               gecko_rsp_mesh_prov_relay_set_id
#define Rsp_mp_reset_node                              gecko_rsp_mesh_prov_reset_node_id
#define Rsp_mp_appkey_get                              gecko_rsp_mesh_prov_appkey_get_id
#define Rsp_mp_network_get                             gecko_rsp_mesh_prov_network_get_id
#define Rsp_mp_model_sub_clear                         gecko_rsp_mesh_prov_model_sub_clear_id
#define Rsp_mp_model_pub_get                           gecko_rsp_mesh_prov_model_pub_get_id
#define Rsp_mp_model_pub_set_va                        gecko_rsp_mesh_prov_model_pub_set_va_id
#define Rsp_mp_model_pub_set_cred                      gecko_rsp_mesh_prov_model_pub_set_cred_id
#define Rsp_mp_model_pub_set_va_cred                   gecko_rsp_mesh_prov_model_pub_set_va_cred_id
#define Rsp_mp_model_sub_get                           gecko_rsp_mesh_prov_model_sub_get_id
#define Rsp_mp_friend_timeout_get                      gecko_rsp_mesh_prov_friend_timeout_get_id
#define Rsp_mp_get_default_config_timeout              gecko_rsp_mesh_prov_get_default_configuration_timeout_id
#define Rsp_mp_set_default_config_timeout              gecko_rsp_mesh_prov_set_default_configuration_timeout_id
#define Rsp_mp_prov_device_with_addr                   gecko_rsp_mesh_prov_provision_device_with_address_id
#define Rsp_mp_prov_gatt_device_with_addr              gecko_rsp_mesh_prov_provision_gatt_device_with_address_id
#define Rsp_mp_initialize_network                      gecko_rsp_mesh_prov_initialize_network_id
#define Rsp_mp_get_key_refresh_appkey_blacklist        gecko_rsp_mesh_prov_get_key_refresh_appkey_blacklist_id
#define Rsp_mp_set_key_refresh_appkey_blacklist        gecko_rsp_mesh_prov_set_key_refresh_appkey_blacklist_id
#define Rsp_mp_stop_scan_unprov_beacons                gecko_rsp_mesh_prov_stop_scan_unprov_beacons_id
#define Rsp_m_proxy_connect                            gecko_rsp_mesh_proxy_connect_id
#define Rsp_m_proxy_disconnect                         gecko_rsp_mesh_proxy_disconnect_id
#define Rsp_m_proxy_set_filter_type                    gecko_rsp_mesh_proxy_set_filter_type_id
#define Rsp_m_proxy_allow                              gecko_rsp_mesh_proxy_allow_id
#define Rsp_m_proxy_deny                               gecko_rsp_mesh_proxy_deny_id
#define Rsp_mv_model_send                              gecko_rsp_mesh_vendor_model_send_id
#define Rsp_mv_model_set_pub                           gecko_rsp_mesh_vendor_model_set_publication_id
#define Rsp_mv_model_clear_pub                         gecko_rsp_mesh_vendor_model_clear_publication_id
#define Rsp_mv_model_publish                           gecko_rsp_mesh_vendor_model_publish_id
#define Rsp_mv_model_init                              gecko_rsp_mesh_vendor_model_init_id
#define Rsp_mv_model_deinit                            gecko_rsp_mesh_vendor_model_deinit_id
#define Rsp_mh_client_get                              gecko_rsp_mesh_health_client_get_id
#define Rsp_mh_client_clear                            gecko_rsp_mesh_health_client_clear_id
#define Rsp_mh_client_test                             gecko_rsp_mesh_health_client_test_id
#define Rsp_mh_client_get_period                       gecko_rsp_mesh_health_client_get_period_id
#define Rsp_mh_client_set_period                       gecko_rsp_mesh_health_client_set_period_id
#define Rsp_mh_client_get_attention                    gecko_rsp_mesh_health_client_get_attention_id
#define Rsp_mh_client_set_attention                    gecko_rsp_mesh_health_client_set_attention_id
#define Rsp_mh_server_set_fault                        gecko_rsp_mesh_health_server_set_fault_id
#define Rsp_mh_server_clear_fault                      gecko_rsp_mesh_health_server_clear_fault_id
#define Rsp_mh_server_test_resp                        gecko_rsp_mesh_health_server_test_response_id
#define Rsp_mg_client_get                              gecko_rsp_mesh_generic_client_get_id
#define Rsp_mg_client_set                              gecko_rsp_mesh_generic_client_set_id
#define Rsp_mg_client_publish                          gecko_rsp_mesh_generic_client_publish_id
#define Rsp_mg_client_get_params                       gecko_rsp_mesh_generic_client_get_params_id
#define Rsp_mg_client_init                             gecko_rsp_mesh_generic_client_init_id
#define Rsp_mg_server_resp                             gecko_rsp_mesh_generic_server_response_id
#define Rsp_mg_server_update                           gecko_rsp_mesh_generic_server_update_id
#define Rsp_mg_server_publish                          gecko_rsp_mesh_generic_server_publish_id
#define Rsp_mg_server_init                             gecko_rsp_mesh_generic_server_init_id
#define Rsp_coex_set_options                           gecko_rsp_coex_set_options_id
#define Rsp_coex_get_counters                          gecko_rsp_coex_get_counters_id
#define Rsp_mt_get_nettx                               gecko_rsp_mesh_test_get_nettx_id
#define Rsp_mt_set_nettx                               gecko_rsp_mesh_test_set_nettx_id
#define Rsp_mt_get_relay                               gecko_rsp_mesh_test_get_relay_id
#define Rsp_mt_set_relay                               gecko_rsp_mesh_test_set_relay_id
#define Rsp_mt_set_adv_scan_params                     gecko_rsp_mesh_test_set_adv_scan_params_id
#define Rsp_mt_set_ivupdate_test_mode                  gecko_rsp_mesh_test_set_ivupdate_test_mode_id
#define Rsp_mt_get_ivupdate_test_mode                  gecko_rsp_mesh_test_get_ivupdate_test_mode_id
#define Rsp_mt_set_segment_send_delay                  gecko_rsp_mesh_test_set_segment_send_delay_id
#define Rsp_mt_set_ivupdate_state                      gecko_rsp_mesh_test_set_ivupdate_state_id
#define Rsp_mt_send_beacons                            gecko_rsp_mesh_test_send_beacons_id
#define Rsp_mt_bind_local_model_app                    gecko_rsp_mesh_test_bind_local_model_app_id
#define Rsp_mt_unbind_local_model_app                  gecko_rsp_mesh_test_unbind_local_model_app_id
#define Rsp_mt_add_local_model_sub                     gecko_rsp_mesh_test_add_local_model_sub_id
#define Rsp_mt_del_local_model_sub                     gecko_rsp_mesh_test_del_local_model_sub_id
#define Rsp_mt_add_local_model_sub_va                  gecko_rsp_mesh_test_add_local_model_sub_va_id
#define Rsp_mt_del_local_model_sub_va                  gecko_rsp_mesh_test_del_local_model_sub_va_id
#define Rsp_mt_get_local_model_sub                     gecko_rsp_mesh_test_get_local_model_sub_id
#define Rsp_mt_set_local_model_pub                     gecko_rsp_mesh_test_set_local_model_pub_id
#define Rsp_mt_set_local_model_pub_va                  gecko_rsp_mesh_test_set_local_model_pub_va_id
#define Rsp_mt_get_local_model_pub                     gecko_rsp_mesh_test_get_local_model_pub_id
#define Rsp_mt_set_local_heartbeat_sub                 gecko_rsp_mesh_test_set_local_heartbeat_subscription_id
#define Rsp_mt_get_local_heartbeat_sub                 gecko_rsp_mesh_test_get_local_heartbeat_subscription_id
#define Rsp_mt_get_local_heartbeat_pub                 gecko_rsp_mesh_test_get_local_heartbeat_publication_id
#define Rsp_mt_set_local_heartbeat_pub                 gecko_rsp_mesh_test_set_local_heartbeat_publication_id
#define Rsp_mt_set_local_config                        gecko_rsp_mesh_test_set_local_config_id
#define Rsp_mt_get_local_config                        gecko_rsp_mesh_test_get_local_config_id
#define Rsp_mt_add_local_key                           gecko_rsp_mesh_test_add_local_key_id
#define Rsp_mt_del_local_key                           gecko_rsp_mesh_test_del_local_key_id
#define Rsp_mt_update_local_key                        gecko_rsp_mesh_test_update_local_key_id
#define Rsp_mt_set_sar_config                          gecko_rsp_mesh_test_set_sar_config_id
#define Rsp_mt_get_element_seqnum                      gecko_rsp_mesh_test_get_element_seqnum_id
#define Rsp_mt_set_adv_bearer_state                    gecko_rsp_mesh_test_set_adv_bearer_state_id
#define Rsp_mt_get_key_count                           gecko_rsp_mesh_test_get_key_count_id
#define Rsp_mt_get_key                                 gecko_rsp_mesh_test_get_key_id
#define Rsp_mt_prov_get_device_key                     gecko_rsp_mesh_test_prov_get_device_key_id
#define Rsp_mt_prov_prepare_key_refresh                gecko_rsp_mesh_test_prov_prepare_key_refresh_id
#define Rsp_mt_cancel_segmented_tx                     gecko_rsp_mesh_test_cancel_segmented_tx_id
#define Rsp_mt_set_iv_index                            gecko_rsp_mesh_test_set_iv_index_id
#define Rsp_mt_set_element_seqnum                      gecko_rsp_mesh_test_set_element_seqnum_id
#define Rsp_m_lpn_init                                 gecko_rsp_mesh_lpn_init_id
#define Rsp_m_lpn_deinit                               gecko_rsp_mesh_lpn_deinit_id
#define Rsp_m_lpn_configure                            gecko_rsp_mesh_lpn_configure_id
#define Rsp_m_lpn_establish_friendship                 gecko_rsp_mesh_lpn_establish_friendship_id
#define Rsp_m_lpn_poll                                 gecko_rsp_mesh_lpn_poll_id
#define Rsp_m_lpn_terminate_friendship                 gecko_rsp_mesh_lpn_terminate_friendship_id
#define Rsp_m_lpn_config                               gecko_rsp_mesh_lpn_config_id
#define Rsp_m_friend_init                              gecko_rsp_mesh_friend_init_id
#define Rsp_m_friend_deinit                            gecko_rsp_mesh_friend_deinit_id
#define Rsp_mc_client_cancel_req                       gecko_rsp_mesh_config_client_cancel_request_id
#define Rsp_mc_client_get_req_status                   gecko_rsp_mesh_config_client_get_request_status_id
#define Rsp_mc_client_get_default_timeout              gecko_rsp_mesh_config_client_get_default_timeout_id
#define Rsp_mc_client_set_default_timeout              gecko_rsp_mesh_config_client_set_default_timeout_id
#define Rsp_mc_client_add_netkey                       gecko_rsp_mesh_config_client_add_netkey_id
#define Rsp_mc_client_remove_netkey                    gecko_rsp_mesh_config_client_remove_netkey_id
#define Rsp_mc_client_list_netkeys                     gecko_rsp_mesh_config_client_list_netkeys_id
#define Rsp_mc_client_add_appkey                       gecko_rsp_mesh_config_client_add_appkey_id
#define Rsp_mc_client_remove_appkey                    gecko_rsp_mesh_config_client_remove_appkey_id
#define Rsp_mc_client_list_appkeys                     gecko_rsp_mesh_config_client_list_appkeys_id
#define Rsp_mc_client_bind_model                       gecko_rsp_mesh_config_client_bind_model_id
#define Rsp_mc_client_unbind_model                     gecko_rsp_mesh_config_client_unbind_model_id
#define Rsp_mc_client_list_bindings                    gecko_rsp_mesh_config_client_list_bindings_id
#define Rsp_mc_client_get_model_pub                    gecko_rsp_mesh_config_client_get_model_pub_id
#define Rsp_mc_client_set_model_pub                    gecko_rsp_mesh_config_client_set_model_pub_id
#define Rsp_mc_client_set_model_pub_va                 gecko_rsp_mesh_config_client_set_model_pub_va_id
#define Rsp_mc_client_add_model_sub                    gecko_rsp_mesh_config_client_add_model_sub_id
#define Rsp_mc_client_add_model_sub_va                 gecko_rsp_mesh_config_client_add_model_sub_va_id
#define Rsp_mc_client_remove_model_sub                 gecko_rsp_mesh_config_client_remove_model_sub_id
#define Rsp_mc_client_remove_model_sub_va              gecko_rsp_mesh_config_client_remove_model_sub_va_id
#define Rsp_mc_client_set_model_sub                    gecko_rsp_mesh_config_client_set_model_sub_id
#define Rsp_mc_client_set_model_sub_va                 gecko_rsp_mesh_config_client_set_model_sub_va_id
#define Rsp_mc_client_clear_model_sub                  gecko_rsp_mesh_config_client_clear_model_sub_id
#define Rsp_mc_client_list_subs                        gecko_rsp_mesh_config_client_list_subs_id
#define Rsp_mc_client_get_heartbeat_pub                gecko_rsp_mesh_config_client_get_heartbeat_pub_id
#define Rsp_mc_client_set_heartbeat_pub                gecko_rsp_mesh_config_client_set_heartbeat_pub_id
#define Rsp_mc_client_get_heartbeat_sub                gecko_rsp_mesh_config_client_get_heartbeat_sub_id
#define Rsp_mc_client_set_heartbeat_sub                gecko_rsp_mesh_config_client_set_heartbeat_sub_id
#define Rsp_mc_client_get_beacon                       gecko_rsp_mesh_config_client_get_beacon_id
#define Rsp_mc_client_set_beacon                       gecko_rsp_mesh_config_client_set_beacon_id
#define Rsp_mc_client_get_default_ttl                  gecko_rsp_mesh_config_client_get_default_ttl_id
#define Rsp_mc_client_set_default_ttl                  gecko_rsp_mesh_config_client_set_default_ttl_id
#define Rsp_mc_client_get_gatt_proxy                   gecko_rsp_mesh_config_client_get_gatt_proxy_id
#define Rsp_mc_client_set_gatt_proxy                   gecko_rsp_mesh_config_client_set_gatt_proxy_id
#define Rsp_mc_client_get_relay                        gecko_rsp_mesh_config_client_get_relay_id
#define Rsp_mc_client_set_relay                        gecko_rsp_mesh_config_client_set_relay_id
#define Rsp_mc_client_get_network_transmit             gecko_rsp_mesh_config_client_get_network_transmit_id
#define Rsp_mc_client_set_network_transmit             gecko_rsp_mesh_config_client_set_network_transmit_id
#define Rsp_mc_client_get_identity                     gecko_rsp_mesh_config_client_get_identity_id
#define Rsp_mc_client_set_identity                     gecko_rsp_mesh_config_client_set_identity_id
#define Rsp_mc_client_get_friend                       gecko_rsp_mesh_config_client_get_friend_id
#define Rsp_mc_client_set_friend                       gecko_rsp_mesh_config_client_set_friend_id
#define Rsp_mc_client_get_lpn_polltimeout              gecko_rsp_mesh_config_client_get_lpn_polltimeout_id
#define Rsp_mc_client_get_dcd                          gecko_rsp_mesh_config_client_get_dcd_id
#define Rsp_mc_client_reset_node                       gecko_rsp_mesh_config_client_reset_node_id
#define Rsp_l2cap_coc_send_connect_req                 gecko_rsp_l2cap_coc_send_connection_request_id
#define Rsp_l2cap_coc_send_connect_resp                gecko_rsp_l2cap_coc_send_connection_response_id
#define Rsp_l2cap_coc_send_le_flow_control_credit      gecko_rsp_l2cap_coc_send_le_flow_control_credit_id
#define Rsp_l2cap_coc_send_disconnect_req              gecko_rsp_l2cap_coc_send_disconnection_request_id
#define Rsp_l2cap_coc_send_data                        gecko_rsp_l2cap_coc_send_data_id
#define Rsp_cte_transmitter_enable_cte_resp            gecko_rsp_cte_transmitter_enable_cte_response_id
#define Rsp_cte_transmitter_disable_cte_resp           gecko_rsp_cte_transmitter_disable_cte_response_id
#define Rsp_cte_transmitter_start_connectless_cte      gecko_rsp_cte_transmitter_start_connectionless_cte_id
#define Rsp_cte_transmitter_stop_connectless_cte       gecko_rsp_cte_transmitter_stop_connectionless_cte_id
#define Rsp_cte_transmitter_set_dtm_parameters         gecko_rsp_cte_transmitter_set_dtm_parameters_id
#define Rsp_cte_transmitter_clear_dtm_parameters       gecko_rsp_cte_transmitter_clear_dtm_parameters_id
#define Rsp_cte_receiver_configure                     gecko_rsp_cte_receiver_configure_id
#define Rsp_cte_receiver_start_iq_sampling             gecko_rsp_cte_receiver_start_iq_sampling_id
#define Rsp_cte_receiver_stop_iq_sampling              gecko_rsp_cte_receiver_stop_iq_sampling_id
#define Rsp_cte_receiver_start_connectless_iq_sampling gecko_rsp_cte_receiver_start_connectionless_iq_sampling_id
#define Rsp_cte_receiver_stop_connectless_iq_sampling  gecko_rsp_cte_receiver_stop_connectionless_iq_sampling_id
#define Rsp_cte_receiver_set_dtm_parameters            gecko_rsp_cte_receiver_set_dtm_parameters_id
#define Rsp_cte_receiver_clear_dtm_parameters          gecko_rsp_cte_receiver_clear_dtm_parameters_id
#define Rsp_ms_server_init                             gecko_rsp_mesh_sensor_server_init_id
#define Rsp_ms_server_deinit                           gecko_rsp_mesh_sensor_server_deinit_id
#define Rsp_ms_server_send_descriptor_status           gecko_rsp_mesh_sensor_server_send_descriptor_status_id
#define Rsp_ms_server_send_status                      gecko_rsp_mesh_sensor_server_send_status_id
#define Rsp_ms_server_send_column_status               gecko_rsp_mesh_sensor_server_send_column_status_id
#define Rsp_ms_server_send_series_status               gecko_rsp_mesh_sensor_server_send_series_status_id
#define Rsp_ms_setup_server_send_cadence_status        gecko_rsp_mesh_sensor_setup_server_send_cadence_status_id
#define Rsp_ms_setup_server_send_settings_status       gecko_rsp_mesh_sensor_setup_server_send_settings_status_id
#define Rsp_ms_setup_server_send_setting_status        gecko_rsp_mesh_sensor_setup_server_send_setting_status_id
#define Rsp_ms_client_init                             gecko_rsp_mesh_sensor_client_init_id
#define Rsp_ms_client_deinit                           gecko_rsp_mesh_sensor_client_deinit_id
#define Rsp_ms_client_get_descriptor                   gecko_rsp_mesh_sensor_client_get_descriptor_id
#define Rsp_ms_client_get                              gecko_rsp_mesh_sensor_client_get_id
#define Rsp_ms_client_get_column                       gecko_rsp_mesh_sensor_client_get_column_id
#define Rsp_ms_client_get_series                       gecko_rsp_mesh_sensor_client_get_series_id
#define Rsp_ms_client_get_cadence                      gecko_rsp_mesh_sensor_client_get_cadence_id
#define Rsp_ms_client_set_cadence                      gecko_rsp_mesh_sensor_client_set_cadence_id
#define Rsp_ms_client_get_settings                	   gecko_rsp_mesh_sensor_client_get_settings_id
#define Rsp_ms_client_get_setting                	  	 gecko_rsp_mesh_sensor_client_get_setting_id
#define Rsp_ms_client_set_setting                      gecko_rsp_mesh_sensor_client_set_setting_id
#define Rsp_user_message_to_target                     gecko_rsp_user_message_to_target_id



// BLE Mesh Event
#define Evt_dfu_boot                                   gecko_evt_dfu_boot_id
#define Evt_dfu_boot_failure                           gecko_evt_dfu_boot_failure_id
#define Evt_sys_boot                                   gecko_evt_system_boot_id
#define Evt_sys_external_signal                        gecko_evt_system_external_signal_id
#define Evt_sys_awake                                  gecko_evt_system_awake_id
#define Evt_sys_hardware_error                         gecko_evt_system_hardware_error_id
#define Evt_sys_error                                  gecko_evt_system_error_id
#define Evt_gap_scan_resp                              gecko_evt_le_gap_scan_response_id
#define Evt_gap_adv_timeout                            gecko_evt_le_gap_adv_timeout_id
#define Evt_gap_scan_req                               gecko_evt_le_gap_scan_request_id
#define Evt_gap_extended_scan_resp                     gecko_evt_le_gap_extended_scan_response_id
#define Evt_gap_periodic_advertising_status            gecko_evt_le_gap_periodic_advertising_status_id
#define Evt_sync_opened                                gecko_evt_sync_opened_id
#define Evt_sync_closed                                gecko_evt_sync_closed_id
#define Evt_sync_data                                  gecko_evt_sync_data_id
#define Evt_connect_opened                             gecko_evt_le_connection_opened_id
#define Evt_connect_closed                             gecko_evt_le_connection_closed_id
#define Evt_connect_parameters                         gecko_evt_le_connection_parameters_id
#define Evt_connect_rssi                               gecko_evt_le_connection_rssi_id
#define Evt_connect_phy_status                         gecko_evt_le_connection_phy_status_id
#define Evt_gatt_mtu_exchanged                         gecko_evt_gatt_mtu_exchanged_id
#define Evt_gatt_service                               gecko_evt_gatt_service_id
#define Evt_gatt_charact                               gecko_evt_gatt_characteristic_id
#define Evt_gatt_descriptor                            gecko_evt_gatt_descriptor_id
#define Evt_gatt_charact_value                         gecko_evt_gatt_characteristic_value_id
#define Evt_gatt_descriptor_value                      gecko_evt_gatt_descriptor_value_id
#define Evt_gatt_procedure_completed                   gecko_evt_gatt_procedure_completed_id
#define Evt_gatt_server_attri_value                    gecko_evt_gatt_server_attribute_value_id
#define Evt_gatt_server_user_read_req                  gecko_evt_gatt_server_user_read_request_id
#define Evt_gatt_server_user_write_req                 gecko_evt_gatt_server_user_write_request_id
#define Evt_gatt_server_charact_status                 gecko_evt_gatt_server_characteristic_status_id
#define Evt_gatt_server_execute_write_completed        gecko_evt_gatt_server_execute_write_completed_id
#define Evt_hardware_soft_timer                        gecko_evt_hardware_soft_timer_id
#define Evt_test_dtm_completed                         gecko_evt_test_dtm_completed_id
#define Evt_sm_passkey_display                         gecko_evt_sm_passkey_display_id
#define Evt_sm_passkey_req                             gecko_evt_sm_passkey_request_id
#define Evt_sm_confirm_passkey                         gecko_evt_sm_confirm_passkey_id
#define Evt_sm_bonded                                  gecko_evt_sm_bonded_id
#define Evt_sm_bonding_failed                          gecko_evt_sm_bonding_failed_id
#define Evt_sm_list_bonding_entry                      gecko_evt_sm_list_bonding_entry_id
#define Evt_sm_list_all_bondings_complete              gecko_evt_sm_list_all_bondings_complete_id
#define Evt_sm_confirm_bonding                         gecko_evt_sm_confirm_bonding_id
#define Evt_hk_setupcode_display                       gecko_evt_homekit_setupcode_display_id
#define Evt_hk_paired                                  gecko_evt_homekit_paired_id
#define Evt_hk_pair_verified                           gecko_evt_homekit_pair_verified_id
#define Evt_hk_connect_opened                          gecko_evt_homekit_connection_opened_id
#define Evt_hk_connect_closed                          gecko_evt_homekit_connection_closed_id
#define Evt_hk_identify                                gecko_evt_homekit_identify_id
#define Evt_hk_write_req                               gecko_evt_homekit_write_request_id
#define Evt_hk_read_req                                gecko_evt_homekit_read_request_id
#define Evt_hk_disconnect_required                     gecko_evt_homekit_disconnection_required_id
#define Evt_hk_pairing_removed                         gecko_evt_homekit_pairing_removed_id
#define Evt_hk_setuppayload_display                    gecko_evt_homekit_setuppayload_display_id
#define Evt_mn_initialized                             gecko_evt_mesh_node_initialized_id
#define Evt_mn_provisioned                             gecko_evt_mesh_node_provisioned_id
#define Evt_mn_config_get                              gecko_evt_mesh_node_config_get_id
#define Evt_mn_config_set                              gecko_evt_mesh_node_config_set_id
#define Evt_mn_display_output_oob                      gecko_evt_mesh_node_display_output_oob_id
#define Evt_mn_input_oob_req                           gecko_evt_mesh_node_input_oob_request_id
#define Evt_mn_provisioning_started                    gecko_evt_mesh_node_provisioning_started_id
#define Evt_mn_provisioning_failed                     gecko_evt_mesh_node_provisioning_failed_id
#define Evt_mn_key_added                               gecko_evt_mesh_node_key_added_id
#define Evt_mn_model_config_changed                    gecko_evt_mesh_node_model_config_changed_id
#define Evt_mn_reset                                   gecko_evt_mesh_node_reset_id
#define Evt_mn_ivrecovery_needed                       gecko_evt_mesh_node_ivrecovery_needed_id
#define Evt_mn_changed_ivupdate_state                  gecko_evt_mesh_node_changed_ivupdate_state_id
#define Evt_mn_static_oob_req                          gecko_evt_mesh_node_static_oob_request_id
#define Evt_mn_key_removed                             gecko_evt_mesh_node_key_removed_id
#define Evt_mn_key_updated                             gecko_evt_mesh_node_key_updated_id
#define Evt_mp_initialized                             gecko_evt_mesh_prov_initialized_id
#define Evt_mp_provisioning_failed                     gecko_evt_mesh_prov_provisioning_failed_id
#define Evt_mp_device_provisioned                      gecko_evt_mesh_prov_device_provisioned_id
#define Evt_mp_unprov_beacon                           gecko_evt_mesh_prov_unprov_beacon_id
#define Evt_mp_dcd_status                              gecko_evt_mesh_prov_dcd_status_id
#define Evt_mp_config_status                           gecko_evt_mesh_prov_config_status_id
#define Evt_mp_oob_pkey_req                            gecko_evt_mesh_prov_oob_pkey_request_id
#define Evt_mp_oob_auth_req                            gecko_evt_mesh_prov_oob_auth_request_id
#define Evt_mp_oob_display_input                       gecko_evt_mesh_prov_oob_display_input_id
#define Evt_mp_ddb_list                                gecko_evt_mesh_prov_ddb_list_id
#define Evt_mp_heartbeat_pub_status                    gecko_evt_mesh_prov_heartbeat_publication_status_id
#define Evt_mp_heartbeat_sub_status                    gecko_evt_mesh_prov_heartbeat_subscription_status_id
#define Evt_mp_relay_status                            gecko_evt_mesh_prov_relay_status_id
#define Evt_mp_uri                                     gecko_evt_mesh_prov_uri_id
#define Evt_mp_node_reset                              gecko_evt_mesh_prov_node_reset_id
#define Evt_mp_appkey_list                             gecko_evt_mesh_prov_appkey_list_id
#define Evt_mp_appkey_list_end                         gecko_evt_mesh_prov_appkey_list_end_id
#define Evt_mp_network_list                            gecko_evt_mesh_prov_network_list_id
#define Evt_mp_network_list_end                        gecko_evt_mesh_prov_network_list_end_id
#define Evt_mp_model_pub_status                        gecko_evt_mesh_prov_model_pub_status_id
#define Evt_mp_key_refresh_phase_update                gecko_evt_mesh_prov_key_refresh_phase_update_id
#define Evt_mp_key_refresh_node_update                 gecko_evt_mesh_prov_key_refresh_node_update_id
#define Evt_mp_key_refresh_complete                    gecko_evt_mesh_prov_key_refresh_complete_id
#define Evt_mp_model_sub_addr                          gecko_evt_mesh_prov_model_sub_addr_id
#define Evt_mp_model_sub_addr_end                      gecko_evt_mesh_prov_model_sub_addr_end_id
#define Evt_mp_friend_timeout_status                   gecko_evt_mesh_prov_friend_timeout_status_id
#define Evt_m_proxy_connected                          gecko_evt_mesh_proxy_connected_id
#define Evt_m_proxy_disconnected                       gecko_evt_mesh_proxy_disconnected_id
#define Evt_m_proxy_filter_status                      gecko_evt_mesh_proxy_filter_status_id
#define Evt_mv_model_receive                           gecko_evt_mesh_vendor_model_receive_id
#define Evt_mh_client_server_status                    gecko_evt_mesh_health_client_server_status_id
#define Evt_mh_client_server_status_period             gecko_evt_mesh_health_client_server_status_period_id
#define Evt_mh_client_server_status_attention          gecko_evt_mesh_health_client_server_status_attention_id
#define Evt_mh_server_attention                        gecko_evt_mesh_health_server_attention_id
#define Evt_mh_server_test_req                         gecko_evt_mesh_health_server_test_request_id
#define Evt_mg_client_server_status                    gecko_evt_mesh_generic_client_server_status_id
#define Evt_mg_server_client_req                       gecko_evt_mesh_generic_server_client_request_id
#define Evt_mg_server_state_changed                    gecko_evt_mesh_generic_server_state_changed_id
#define Evt_mt_local_heartbeat_sub_complete            gecko_evt_mesh_test_local_heartbeat_subscription_complete_id
#define Evt_m_lpn_friendship_established               gecko_evt_mesh_lpn_friendship_established_id
#define Evt_m_lpn_friendship_failed                    gecko_evt_mesh_lpn_friendship_failed_id
#define Evt_m_lpn_friendship_terminated                gecko_evt_mesh_lpn_friendship_terminated_id
#define Evt_m_friend_friendship_established            gecko_evt_mesh_friend_friendship_established_id
#define Evt_m_friend_friendship_terminated             gecko_evt_mesh_friend_friendship_terminated_id
#define Evt_mc_client_req_modified                     gecko_evt_mesh_config_client_request_modified_id
#define Evt_mc_client_netkey_status                    gecko_evt_mesh_config_client_netkey_status_id
#define Evt_mc_client_netkey_list                      gecko_evt_mesh_config_client_netkey_list_id
#define Evt_mc_client_netkey_list_end                  gecko_evt_mesh_config_client_netkey_list_end_id
#define Evt_mc_client_appkey_status                    gecko_evt_mesh_config_client_appkey_status_id
#define Evt_mc_client_appkey_list                      gecko_evt_mesh_config_client_appkey_list_id
#define Evt_mc_client_appkey_list_end                  gecko_evt_mesh_config_client_appkey_list_end_id
#define Evt_mc_client_binding_status                   gecko_evt_mesh_config_client_binding_status_id
#define Evt_mc_client_bindings_list                    gecko_evt_mesh_config_client_bindings_list_id
#define Evt_mc_client_bindings_list_end                gecko_evt_mesh_config_client_bindings_list_end_id
#define Evt_mc_client_model_pub_status                 gecko_evt_mesh_config_client_model_pub_status_id
#define Evt_mc_client_model_sub_status                 gecko_evt_mesh_config_client_model_sub_status_id
#define Evt_mc_client_subs_list                        gecko_evt_mesh_config_client_subs_list_id
#define Evt_mc_client_subs_list_end                    gecko_evt_mesh_config_client_subs_list_end_id
#define Evt_mc_client_heartbeat_pub_status             gecko_evt_mesh_config_client_heartbeat_pub_status_id
#define Evt_mc_client_heartbeat_sub_status             gecko_evt_mesh_config_client_heartbeat_sub_status_id
#define Evt_mc_client_beacon_status                    gecko_evt_mesh_config_client_beacon_status_id
#define Evt_mc_client_default_ttl_status               gecko_evt_mesh_config_client_default_ttl_status_id
#define Evt_mc_client_gatt_proxy_status                gecko_evt_mesh_config_client_gatt_proxy_status_id
#define Evt_mc_client_relay_status                     gecko_evt_mesh_config_client_relay_status_id
#define Evt_mc_client_network_transmit_status          gecko_evt_mesh_config_client_network_transmit_status_id
#define Evt_mc_client_identity_status                  gecko_evt_mesh_config_client_identity_status_id
#define Evt_mc_client_friend_status                    gecko_evt_mesh_config_client_friend_status_id
#define Evt_mc_client_lpn_polltimeout_status           gecko_evt_mesh_config_client_lpn_polltimeout_status_id
#define Evt_mc_client_dcd_data                         gecko_evt_mesh_config_client_dcd_data_id
#define Evt_mc_client_dcd_data_end                     gecko_evt_mesh_config_client_dcd_data_end_id
#define Evt_mc_client_reset_status                     gecko_evt_mesh_config_client_reset_status_id
#define Evt_l2cap_coc_connect_req                      gecko_evt_l2cap_coc_connection_request_id
#define Evt_l2cap_coc_connect_resp                     gecko_evt_l2cap_coc_connection_response_id
#define Evt_l2cap_coc_le_flow_control_credit           gecko_evt_l2cap_coc_le_flow_control_credit_id
#define Evt_l2cap_coc_channel_disconnected             gecko_evt_l2cap_coc_channel_disconnected_id
#define Evt_l2cap_coc_data                             gecko_evt_l2cap_coc_data_id
#define Evt_l2cap_command_rejected                     gecko_evt_l2cap_command_rejected_id
#define Evt_cte_receiver_iq_report                     gecko_evt_cte_receiver_iq_report_id
#define Evt_ms_server_get_req                          gecko_evt_mesh_sensor_server_get_request_id
#define Evt_ms_server_get_column_req                   gecko_evt_mesh_sensor_server_get_column_request_id
#define Evt_ms_server_get_series_req                   gecko_evt_mesh_sensor_server_get_series_request_id
#define Evt_ms_server_publish                          gecko_evt_mesh_sensor_server_publish_id
#define Evt_ms_setup_server_get_cadence_req            gecko_evt_mesh_sensor_setup_server_get_cadence_request_id
#define Evt_ms_setup_server_set_cadence_req            gecko_evt_mesh_sensor_setup_server_set_cadence_request_id
#define Evt_ms_setup_server_get_settings_req           gecko_evt_mesh_sensor_setup_server_get_settings_request_id
#define Evt_ms_setup_server_get_setting_req            gecko_evt_mesh_sensor_setup_server_get_setting_request_id
#define Evt_ms_setup_server_set_setting_req            gecko_evt_mesh_sensor_setup_server_set_setting_request_id
#define Evt_ms_setup_server_publish                    gecko_evt_mesh_sensor_setup_server_publish_id
#define Evt_ms_client_descriptor_status                gecko_evt_mesh_sensor_client_descriptor_status_id
#define Evt_ms_client_cadence_status                   gecko_evt_mesh_sensor_client_cadence_status_id
#define Evt_ms_client_settings_status                  gecko_evt_mesh_sensor_client_settings_status_id
#define Evt_ms_client_setting_status                   gecko_evt_mesh_sensor_client_setting_status_id
#define Evt_ms_client_status                           gecko_evt_mesh_sensor_client_status_id
#define Evt_ms_client_column_status                    gecko_evt_mesh_sensor_client_column_status_id
#define Evt_ms_client_series_status                    gecko_evt_mesh_sensor_client_series_status_id
#define Evt_ms_client_publish                          gecko_evt_mesh_sensor_client_publish_id
#define Evt_user_message_to_host                       gecko_evt_user_message_to_host_id

#endif

void EventIDtoStringProc(PCmdPacket pEvent);




