#include "global.h"

#include "ble_msg.h"
#include "cmd_rsp_evt.h"

EventIDToString EventIDStrTbl[] =
{
    // For Event
  {Evt_dfu_boot                                ,"evt_dfu_boot"},                                         
  {Evt_dfu_boot_failure                        ,"evt_dfu_boot_failure"},                                 
  {Evt_sys_boot                                ,"evt_system_boot"},                                      
  {Evt_sys_external_signal                     ,"evt_system_external_signal"},                           
  {Evt_sys_awake                               ,"evt_system_awake"},                                     
  {Evt_sys_hardware_error                      ,"evt_system_hardware_error"},                            
  {Evt_sys_error                               ,"evt_system_error"},                                     
  {Evt_gap_scan_resp                           ,"evt_le_gap_scan_response"},                             
  {Evt_gap_adv_timeout                         ,"evt_le_gap_adv_timeout"},                               
  {Evt_gap_scan_req                            ,"evt_le_gap_scan_request"},                              
  {Evt_gap_extended_scan_resp                  ,"evt_le_gap_extended_scan_response"},                    
  {Evt_gap_periodic_advertising_status         ,"evt_le_gap_periodic_advertising_status"},               
  {Evt_sync_opened                             ,"evt_sync_opened"},                                      
  {Evt_sync_closed                             ,"evt_sync_closed"},                                      
  {Evt_sync_data                               ,"evt_sync_data"},                                        
  {Evt_connect_opened                          ,"evt_le_connection_opened"},                             
  {Evt_connect_closed                          ,"evt_le_connection_closed"},                             
  {Evt_connect_parameters                      ,"evt_le_connection_parameters"},                         
  {Evt_connect_rssi                            ,"evt_le_connection_rssi"},                               
  {Evt_connect_phy_status                      ,"evt_le_connection_phy_status"},                         
  {Evt_gatt_mtu_exchanged                      ,"evt_gatt_mtu_exchanged"},                               
  {Evt_gatt_service                            ,"evt_gatt_service"},                                     
  {Evt_gatt_charact                            ,"evt_gatt_characteristic"},                              
  {Evt_gatt_descriptor                         ,"evt_gatt_descriptor"},                                  
  {Evt_gatt_charact_value                      ,"evt_gatt_characteristic_value"},                        
  {Evt_gatt_descriptor_value                   ,"evt_gatt_descriptor_value"},                            
  {Evt_gatt_procedure_completed                ,"evt_gatt_procedure_completed"},                         
  {Evt_gatt_server_attri_value                 ,"evt_gatt_server_attribute_value"},                      
  {Evt_gatt_server_user_read_req               ,"evt_gatt_server_user_read_request"},                    
  {Evt_gatt_server_user_write_req              ,"evt_gatt_server_user_write_request"},                   
  {Evt_gatt_server_charact_status              ,"evt_gatt_server_characteristic_status"},                
  {Evt_gatt_server_execute_write_completed     ,"evt_gatt_server_execute_write_completed"},              
  {Evt_hardware_soft_timer                     ,"evt_hardware_soft_timer"},                              
  {Evt_test_dtm_completed                      ,"evt_test_dtm_completed"},                               
  {Evt_sm_passkey_display                      ,"evt_sm_passkey_display"},                               
  {Evt_sm_passkey_req                          ,"evt_sm_passkey_request"},                               
  {Evt_sm_confirm_passkey                      ,"evt_sm_confirm_passkey"},                               
  {Evt_sm_bonded                               ,"evt_sm_bonded"},                                        
  {Evt_sm_bonding_failed                       ,"evt_sm_bonding_failed"},                                
  {Evt_sm_list_bonding_entry                   ,"evt_sm_list_bonding_entry"},                            
  {Evt_sm_list_all_bondings_complete           ,"evt_sm_list_all_bondings_complete"},                    
  {Evt_sm_confirm_bonding                      ,"evt_sm_confirm_bonding"},                               
  {Evt_hk_setupcode_display                    ,"evt_homekit_setupcode_display"},                        
  {Evt_hk_paired                               ,"evt_homekit_paired"},                                   
  {Evt_hk_pair_verified                        ,"evt_homekit_pair_verified"},                            
  {Evt_hk_connect_opened                       ,"evt_homekit_connection_opened"},                        
  {Evt_hk_connect_closed                       ,"evt_homekit_connection_closed"},                        
  {Evt_hk_identify                             ,"evt_homekit_identify"},                                 
  {Evt_hk_write_req                            ,"evt_homekit_write_request"},                            
  {Evt_hk_read_req                             ,"evt_homekit_read_request"},                             
  {Evt_hk_disconnect_required                  ,"evt_homekit_disconnection_required"},                   
  {Evt_hk_pairing_removed                      ,"evt_homekit_pairing_removed"},                          
  {Evt_hk_setuppayload_display                 ,"evt_homekit_setuppayload_display"},                     
  {Evt_mn_initialized                          ,"evt_mesh_node_initialized"},                            
  {Evt_mn_provisioned                          ,"evt_mesh_node_provisioned"},                            
  {Evt_mn_config_get                           ,"evt_mesh_node_config_get"},                             
  {Evt_mn_config_set                           ,"evt_mesh_node_config_set"},                             
  {Evt_mn_display_output_oob                   ,"evt_mesh_node_display_output_oob"},                     
  {Evt_mn_input_oob_req                        ,"evt_mesh_node_input_oob_request"},                      
  {Evt_mn_provisioning_started                 ,"evt_mesh_node_provisioning_started"},                   
  {Evt_mn_provisioning_failed                  ,"evt_mesh_node_provisioning_failed"},                    
  {Evt_mn_key_added                            ,"evt_mesh_node_key_added"},                              
  {Evt_mn_model_config_changed                 ,"evt_mesh_node_model_config_changed"},                   
  {Evt_mn_reset                                ,"evt_mesh_node_reset"},                                  
  {Evt_mn_ivrecovery_needed                    ,"evt_mesh_node_ivrecovery_needed"},                      
  {Evt_mn_changed_ivupdate_state               ,"evt_mesh_node_changed_ivupdate_state"},                 
  {Evt_mn_static_oob_req                       ,"evt_mesh_node_static_oob_request"},                     
  {Evt_mn_key_removed                          ,"evt_mesh_node_key_removed"},                            
  {Evt_mn_key_updated                          ,"evt_mesh_node_key_updated"},                            
  {Evt_mp_initialized                          ,"evt_mesh_prov_initialized"},                            
  {Evt_mp_provisioning_failed                  ,"evt_mesh_prov_provisioning_failed"},                    
  {Evt_mp_device_provisioned                   ,"evt_mesh_prov_device_provisioned"},                     
  {Evt_mp_unprov_beacon                        ,"evt_mesh_prov_unprov_beacon"},                          
  {Evt_mp_dcd_status                           ,"evt_mesh_prov_dcd_status"},                             
  {Evt_mp_config_status                        ,"evt_mesh_prov_config_status"},                          
  {Evt_mp_oob_pkey_req                         ,"evt_mesh_prov_oob_pkey_request"},                       
  {Evt_mp_oob_auth_req                         ,"evt_mesh_prov_oob_auth_request"},                       
  {Evt_mp_oob_display_input                    ,"evt_mesh_prov_oob_display_input"},                      
  {Evt_mp_ddb_list                             ,"evt_mesh_prov_ddb_list"},                               
  {Evt_mp_heartbeat_pub_status                 ,"evt_mesh_prov_heartbeat_publication_status"},           
  {Evt_mp_heartbeat_sub_status                 ,"evt_mesh_prov_heartbeat_subscription_status"},          
  {Evt_mp_relay_status                         ,"evt_mesh_prov_relay_status"},                           
  {Evt_mp_uri                                  ,"evt_mesh_prov_uri"},                                    
  {Evt_mp_node_reset                           ,"evt_mesh_prov_node_reset"},                             
  {Evt_mp_appkey_list                          ,"evt_mesh_prov_appkey_list"},                            
  {Evt_mp_appkey_list_end                      ,"evt_mesh_prov_appkey_list_end"},                        
  {Evt_mp_network_list                         ,"evt_mesh_prov_network_list"},                           
  {Evt_mp_network_list_end                     ,"evt_mesh_prov_network_list_end"},                       
  {Evt_mp_model_pub_status                     ,"evt_mesh_prov_model_pub_status"},                       
  {Evt_mp_key_refresh_phase_update             ,"evt_mesh_prov_key_refresh_phase_update"},               
  {Evt_mp_key_refresh_node_update              ,"evt_mesh_prov_key_refresh_node_update"},                
  {Evt_mp_key_refresh_complete                 ,"evt_mesh_prov_key_refresh_complete"},                   
  {Evt_mp_model_sub_addr                       ,"evt_mesh_prov_model_sub_addr"},                         
  {Evt_mp_model_sub_addr_end                   ,"evt_mesh_prov_model_sub_addr_end"},                     
  {Evt_mp_friend_timeout_status                ,"evt_mesh_prov_friend_timeout_status"},                  
  {Evt_m_proxy_connected                       ,"evt_mesh_proxy_connected"},                             
  {Evt_m_proxy_disconnected                    ,"evt_mesh_proxy_disconnected"},                          
  {Evt_m_proxy_filter_status                   ,"evt_mesh_proxy_filter_status"},                         
  {Evt_mv_model_receive                        ,"evt_mesh_vendor_model_receive"},                        
  {Evt_mh_client_server_status                 ,"evt_mesh_health_client_server_status"},                 
  {Evt_mh_client_server_status_period          ,"evt_mesh_health_client_server_status_period"},          
  {Evt_mh_client_server_status_attention       ,"evt_mesh_health_client_server_status_attention"},       
  {Evt_mh_server_attention                     ,"evt_mesh_health_server_attention"},                     
  {Evt_mh_server_test_req                      ,"evt_mesh_health_server_test_request"},                  
  {Evt_mg_client_server_status                 ,"evt_mesh_generic_client_server_status"},                
  {Evt_mg_server_client_req                    ,"evt_mesh_generic_server_client_request"},               
  {Evt_mg_server_state_changed                 ,"evt_mesh_generic_server_state_changed"},                
  {Evt_mt_local_heartbeat_sub_complete         ,"evt_mesh_test_local_heartbeat_subscription_complete"},  
  {Evt_m_lpn_friendship_established            ,"evt_mesh_lpn_friendship_established"},                  
  {Evt_m_lpn_friendship_failed                 ,"evt_mesh_lpn_friendship_failed"},                       
  {Evt_m_lpn_friendship_terminated             ,"evt_mesh_lpn_friendship_terminated"},                   
  {Evt_m_friend_friendship_established         ,"evt_mesh_friend_friendship_established"},               
  {Evt_m_friend_friendship_terminated          ,"evt_mesh_friend_friendship_terminated"},                
  {Evt_mc_client_req_modified                  ,"evt_mesh_config_client_request_modified"},              
  {Evt_mc_client_netkey_status                 ,"evt_mesh_config_client_netkey_status"},                 
  {Evt_mc_client_netkey_list                   ,"evt_mesh_config_client_netkey_list"},                   
  {Evt_mc_client_netkey_list_end               ,"evt_mesh_config_client_netkey_list_end"},               
  {Evt_mc_client_appkey_status                 ,"evt_mesh_config_client_appkey_status"},                 
  {Evt_mc_client_appkey_list                   ,"evt_mesh_config_client_appkey_list"},                   
  {Evt_mc_client_appkey_list_end               ,"evt_mesh_config_client_appkey_list_end"},               
  {Evt_mc_client_binding_status                ,"evt_mesh_config_client_binding_status"},                
  {Evt_mc_client_bindings_list                 ,"evt_mesh_config_client_bindings_list"},                 
  {Evt_mc_client_bindings_list_end             ,"evt_mesh_config_client_bindings_list_end"},             
  {Evt_mc_client_model_pub_status              ,"evt_mesh_config_client_model_pub_status"},              
  {Evt_mc_client_model_sub_status              ,"evt_mesh_config_client_model_sub_status"},              
  {Evt_mc_client_subs_list                     ,"evt_mesh_config_client_subs_list"},                     
  {Evt_mc_client_subs_list_end                 ,"evt_mesh_config_client_subs_list_end"},                 
  {Evt_mc_client_heartbeat_pub_status          ,"evt_mesh_config_client_heartbeat_pub_status"},          
  {Evt_mc_client_heartbeat_sub_status          ,"evt_mesh_config_client_heartbeat_sub_status"},          
  {Evt_mc_client_beacon_status                 ,"evt_mesh_config_client_beacon_status"},                 
  {Evt_mc_client_default_ttl_status            ,"evt_mesh_config_client_default_ttl_status"},            
  {Evt_mc_client_gatt_proxy_status             ,"evt_mesh_config_client_gatt_proxy_status"},             
  {Evt_mc_client_relay_status                  ,"evt_mesh_config_client_relay_status"},                  
  {Evt_mc_client_network_transmit_status       ,"evt_mesh_config_client_network_transmit_status"},       
  {Evt_mc_client_identity_status               ,"evt_mesh_config_client_identity_status"},               
  {Evt_mc_client_friend_status                 ,"evt_mesh_config_client_friend_status"},                 
  {Evt_mc_client_lpn_polltimeout_status        ,"evt_mesh_config_client_lpn_polltimeout_status"},        
  {Evt_mc_client_dcd_data                      ,"evt_mesh_config_client_dcd_data"},                      
  {Evt_mc_client_dcd_data_end                  ,"evt_mesh_config_client_dcd_data_end"},                  
  {Evt_mc_client_reset_status                  ,"evt_mesh_config_client_reset_status"},                  
  {Evt_l2cap_coc_connect_req                   ,"evt_l2cap_coc_connection_request"},                     
  {Evt_l2cap_coc_connect_resp                  ,"evt_l2cap_coc_connection_response"},                    
  {Evt_l2cap_coc_le_flow_control_credit        ,"evt_l2cap_coc_le_flow_control_credit"},                 
  {Evt_l2cap_coc_channel_disconnected          ,"evt_l2cap_coc_channel_disconnected"},                   
  {Evt_l2cap_coc_data                          ,"evt_l2cap_coc_data"},                                   
  {Evt_l2cap_command_rejected                  ,"evt_l2cap_command_rejected"},                           
  {Evt_cte_receiver_iq_report                  ,"evt_cte_receiver_iq_report"},                           
  {Evt_ms_server_get_req                       ,"evt_mesh_sensor_server_get_request"},                   
  {Evt_ms_server_get_column_req                ,"evt_mesh_sensor_server_get_column_request"},            
  {Evt_ms_server_get_series_req                ,"evt_mesh_sensor_server_get_series_request"},            
  {Evt_ms_server_publish                       ,"evt_mesh_sensor_server_publish"},                       
  {Evt_ms_setup_server_get_cadence_req         ,"evt_mesh_sensor_setup_server_get_cadence_request"},     
  {Evt_ms_setup_server_set_cadence_req         ,"evt_mesh_sensor_setup_server_set_cadence_request"},     
  {Evt_ms_setup_server_get_settings_req        ,"evt_mesh_sensor_setup_server_get_settings_request"},    
  {Evt_ms_setup_server_get_setting_req         ,"evt_mesh_sensor_setup_server_get_setting_request"},     
  {Evt_ms_setup_server_set_setting_req         ,"evt_mesh_sensor_setup_server_set_setting_request"},     
  {Evt_ms_setup_server_publish                 ,"evt_mesh_sensor_setup_server_publish"},                 
  {Evt_ms_client_descriptor_status             ,"evt_mesh_sensor_client_descriptor_status"},             
  {Evt_ms_client_cadence_status                ,"evt_mesh_sensor_client_cadence_status"},                
  {Evt_ms_client_settings_status               ,"evt_mesh_sensor_client_settings_status"},               
  {Evt_ms_client_setting_status                ,"evt_mesh_sensor_client_setting_status"},                
  {Evt_ms_client_status                        ,"evt_mesh_sensor_client_status"},                        
  {Evt_ms_client_column_status                 ,"evt_mesh_sensor_client_column_status"},                 
  {Evt_ms_client_series_status                 ,"evt_mesh_sensor_client_series_status"},                 
  {Evt_ms_client_publish                       ,"evt_mesh_sensor_client_publish"},                       
  {Evt_user_message_to_host                    ,"evt_user_message_to_host"},

{0,0}
};

void EventIDtoStringProc(PCmdPacket pEvent)
{
    PEventIDToString pTable;
    uint32 event_id;
    event_id = BGLIB_MSG_ID(pEvent->header); //get event ID
    pTable = EventIDStrTbl;
    while(pTable->pString != NULL)
        {
            if(pTable->event_id == event_id)
                {
                printf("xxxx Lose %s = 0x%08lX xxx\r\n",pTable->pString,event_id);
                break;
                }
            pTable++;
        };
   if(pTable->pString == NULL) Trace1("No BLE Mesh Cmd ID To Display",event_id);     
}

